### ISSUE TITLE
[Ombi] - Fehler beim Abruf der IMDb

### ISSUE THREAD

**Issue by jankete** [rix1337/FeedCrawler#518]
# [FeedCrawler] Fehlermeldung

## Zwingend erforderlich

- **Fehlermeldung aus dem Log** (ggf. DEBUG aktivieren!)
[Ombi] - Fehler beim Abruf der IMDb für: tt3228774

- **Genutzte Version** (kein Support für alte Releases)
11.0.3

- **Wird Python 3.9 oder aktueller genutzt?**
Docker

## Fehlerbeschreibung

Der Crawler stellt korrekt die Verbindung zu Ombi her und erkennt einen neu hinzugefügten Film. Dann erscheint im Log der o.g. Fehler. Der manuelle Aufruf mit der IMDb-ID (https://www.imdb.com/title/tt3228774/) funktioniert aber.

**Comment by 9Mad-Max5** [comment]
Kann ich bestätigen habe das gleiche Problem.
