### ISSUE TITLE
Doppelte Ergebnisse

### ISSUE THREAD

**Issue by jankete** [rix1337/FeedCrawler#519]
# [FeedCrawler] Fehlermeldung

## Zwingend erforderlich

- **Fehlermeldung aus dem Log** (ggf. DEBUG aktivieren!)
Suchergebnisse erscheinen im Log (Docker-Console und Frontend) jeweils doppelt.

- **Genutzte Version** (kein Support für alte Releases)
11.0.3

- **Wird Python 3.9 oder aktueller genutzt?**
Docker

## Fehlerbeschreibung

Findet der Crawler Episoden (z.B. bei SJ oder DW) tauchen sie doppelt im Log auf. Dies ist sowohl auf der Docker-Console, als auch im Frontend zu sehen.

`[Episode/RegEx] - W[...].German.DD51.Dubbed.DL.720p.AmazonHD.AVC-TVS  - [DW]
[Episode/RegEx] - W[...].German.DD51.Dubbed.DL.720p.AmazonHD.AVC-TVS  - [DW]
2021-06-10 22:17:31 - Alle Suchfunktion ausgeführt (Dauer: 00:01:46)! Der FeedCrawler-Cache hat 83 HTTP-Requests gespart!`

![2021-06-11 07_39_55-FeedCrawler](https://user-images.githubusercontent.com/22338766/121636589-64c61c00-ca88-11eb-8d0d-89d1e4452ce3.png)

Das Paket selbst wird aber nur 1x an den Helper bzw. JD übergeben.

**Comment by rix1337** [comment]
Nicht nachstellbar. Vielleicht liegts an deinen speziellen Einstellungen. Schick mir ini und db per PN auf gitter.
