### ISSUE TITLE
Autostart nach jD-Update

### ISSUE THREAD

**Issue by jankete** [rix1337/FeedCrawler#540]
# [FeedCrawler] Fehlermeldung

## Zwingend erforderlich

- **Fehlermeldung aus dem Log** (ggf. DEBUG aktivieren!)
keine

- **Genutzte Version** (kein Support für alte Releases)
11.0.16

- **Wird Python 3.9 oder aktueller genutzt?**
Docker-Image

## Fehlerbeschreibung

Der jDownloader wird regelmäßig mit Updates versorgt. Werden diese installiert und der jDownloader anschließend neu gestartet funktioniert zwar die Paketübergabe des Crawlers an den jDownloader noch, der Autostart des Downloads allerdings nicht mehr. Erst nachdem auch der Docker-Container des FeedCrawlers neu gestartet wurde, klappt auch der Autostart wieder.

**Comment by rix1337** [comment]
Ursache ist nicht trivial festzustellen. Wenn mir etwas auffällt, kommt ein Fix.

**Comment by rix1337** [comment]
Temporäre Lösung ist, die Updatefunktion im Webinterface zu deaktivieren. Damit verhindern wir das ungewollte Verhalten zumindest seitens FeedCrawler. Wer den JDownloader manuell updated, während FeedCrawler läuft, sollte auch diesen neu starten - Readme ergänzt.

**Comment by rix1337** [comment]
In Version 11.0.19 wurde eine Umgehung aktiviert und das Readme entsprechend ergänzt.
