### ISSUE TITLE
Erkennung von Multi-Episoden

### ISSUE THREAD

**Issue by jankete** [rix1337/FeedCrawler#541]
# [FeedCrawler] Fehlermeldung

## Zwingend erforderlich

- **Fehlermeldung aus dem Log** (ggf. DEBUG aktivieren!)
keine

- **Genutzte Version** (kein Support für alte Releases)
11.0.16

- **Wird Python 3.9 oder aktueller genutzt?**
Docker-Image

## Fehlerbeschreibung

Die Erkennung von Multi-Episoden-Paketen funktioniert noch nicht optimal. 

Beispiel:
"SERIE.S01E05.-.E06.German.DL.720p.XXXXX" von DW wird offenbar nur als S01E05 erkannt, weshalb dann auch "SERIE.S01E06.German.DL.720p.XXXXX" von SJ noch hinzugefügt wird. Somit wird die E06 am Ende quasi doppelt heruntergeladen.

Die Suche erfolgte hierbei über die normale Serienliste (nicht RegEx).

**Comment by rix1337** [comment]
Mögliche Ursache gefunden, aber nicht trivial zu beheben. Sobald gelöst, kommt ein Fix.
