### ISSUE TITLE
Kein Match mehr seit v.12.0.0

### ISSUE THREAD

**Issue by DKeppi** [rix1337/FeedCrawler#557]
Arbeite mit SJ und habe folgende Liste:

```
American.Crime.Story.*.WEBRiP.X264-LAW
Die.Simpsons.*.WEBRiP.x264-GERTv
Final.Space.*.480p.AmazonHD.x264-GDR
Leverage.Redemption.*.X264-4SJ
Mr.Inbetween.*.WEBRiP.x264-4SJ
Rick.and.Morty.*.WEBRiP.X264-4SJ
Riverdale.*.WEBRiP.x264-4SJ
The.Walking.Dead.*.WEBRiP.X264-4SJ
Undercover.2019.*.WEBRiP.X264-4SJ
Young.Sheldon.*.WEBRiP.x264-4SJ
```

Für `Leverage.Redemption.*.X264-4SJ` sollte eigentlich etwas gefunden werden, tut es aber nicht.

Leider hilft mir das Debug Log auch nicht weiter :(

**-----------Wartezeit bis zum nächsten Suchlauf: 00:10:22-----------
----------Wartezeit vorzeitig beendet----------
Disabled request caching for request of: https://SJ
--------Alle Suchfunktion gestartet.--------
-----------Suchfunktion (FX - Liste: List_ContentAll_Movies_Regex) gestartet!-----------
Regex deaktiviert. Stoppe Suche für Filme! (List_ContentAll_Movies_Regex)
-----------Suchfunktion (FX - Liste: List_ContentAll_Movies_Regex) ausgeführt!-----------
-----------Suchfunktion (FX - Liste: IMDB) gestartet!-----------
Kein Hostname gesetzt. Stoppe Suche für Filme! (IMDB)
-----------Suchfunktion (FX - Liste: IMDB) ausgeführt!-----------
-----------Suchfunktion (FX - Liste: List_ContentAll_Movies) gestartet!-----------
Kein Hostname gesetzt. Stoppe Suche für Filme! (List_ContentAll_Movies)
-----------Suchfunktion (FX - Liste: List_ContentAll_Movies) ausgeführt!-----------
-----------Suchfunktion (FX - Liste: List_ContentAll_Seasons) gestartet!-----------
-----------Suchfunktion (FX - Liste: List_ContentAll_Seasons) ausgeführt!-----------
-----------Suchfunktion (SJ - Liste: List_ContentShows_Shows) gestartet!-----------
Liste ist leer. Stoppe Suche für Serien!
-----------Suchfunktion (SJ - Liste: List_ContentShows_Shows) ausgeführt!-----------
-----------Suchfunktion (SJ - Liste: List_ContentShows_Shows_Regex) gestartet!-----------
Young.Sheldon.S05E01.DL.GERMAN.WEBRiP.X264-4SJ - Release ignoriert (Gleiche oder bessere Quelle bereits vorhanden)
Undercover.2019.S03E04.GERMAN.WEBRiP.X264-4SJ - Release ignoriert (Gleiche oder bessere Quelle bereits vorhanden)
Undercover.2019.S03E03.GERMAN.WEBRiP.X264-4SJ - Release ignoriert (Gleiche oder bessere Quelle bereits vorhanden)
Undercover.2019.S03E02.GERMAN.WEBRiP.X264-4SJ - Release ignoriert (Gleiche oder bessere Quelle bereits vorhanden)
Undercover.2019.S03E01.GERMAN.WEBRiP.X264-4SJ - Release ignoriert (Gleiche oder bessere Quelle bereits vorhanden)
Undercover.2019.S02E01-S02E10.DL.GERMAN.WEBRiP.x264-4SJ - Release ignoriert (Gleiche oder bessere Quelle bereits vorhanden)
Rick.And.Morty.S05E10.DL.GERMAN.WEBRiP.X264-4SJ - Release ignoriert (Gleiche oder bessere Quelle bereits vorhanden)
Rick.And.Morty.S05E09.DL.GERMAN.WEBRiP.X264-4SJ - Release ignoriert (Gleiche oder bessere Quelle bereits vorhanden)
Riverdale.S06E04.DL.GERMAN.WEBRiP.X264-4SJ - Release ignoriert (Gleiche oder bessere Quelle bereits vorhanden)
Young.Sheldon.S04E18.DL.GERMAN.WEBRiP.X264-4SJ - Release ignoriert (Gleiche oder bessere Quelle bereits vorhanden)
Young.Sheldon.S04E17.DL.GERMAN.WEBRiP.X264-4SJ - Release ignoriert (Gleiche oder bessere Quelle bereits vorhanden)
-----------Suchfunktion (SJ - Liste: List_ContentShows_Shows_Regex) ausgeführt!-----------
-----------Suchfunktion (SJ - Liste: List_ContentShows_Seasons_Regex) gestartet!-----------
Liste ist leer. Stoppe Suche für Serien! (Staffeln/RegEx)
-----------Suchfunktion (SJ - Liste: List_ContentShows_Seasons_Regex) ausgeführt!-----------
-----------Suchfunktion (SJ - Liste: List_ContentAll_Seasons) gestartet!-----------
Suche für SJ-Staffeln deaktiviert!
-----------Suchfunktion (SJ - Liste: List_ContentAll_Seasons) ausgeführt!-----------
-----------Suchfunktion (DJ - Liste: List_CustomDJ_Documentaries) gestartet!-----------
-----------Suchfunktion (DJ - Liste: List_CustomDJ_Documentaries) ausgeführt!-----------
-----------Suchfunktion (DJ - Liste: List_CustomDJ_Documentaries_Regex) gestartet!-----------
-----------Suchfunktion (DJ - Liste: List_CustomDJ_Documentaries_Regex) ausgeführt!-----------
-----------Suchfunktion (SF - Liste: List_ContentShows_Shows) gestartet!-----------
-----------Suchfunktion (SF - Liste: List_ContentShows_Shows) ausgeführt!-----------
-----------Suchfunktion (SF - Liste: List_ContentShows_Shows_Regex) gestartet!-----------
-----------Suchfunktion (SF - Liste: List_ContentShows_Shows_Regex) ausgeführt!-----------
-----------Suchfunktion (SF - Liste: List_ContentShows_Seasons_Regex) gestartet!-----------
-----------Suchfunktion (SF - Liste: List_ContentShows_Seasons_Regex) ausgeführt!-----------
-----------Suchfunktion (SF - Liste: List_ContentAll_Seasons) gestartet!-----------
-----------Suchfunktion (SF - Liste: List_ContentAll_Seasons) ausgeführt!-----------
-----------Suchfunktion (WW - Liste: List_ContentAll_Movies_Regex) gestartet!-----------
Regex deaktiviert. Stoppe Suche für Filme! (List_ContentAll_Movies_Regex)
-----------Suchfunktion (WW - Liste: List_ContentAll_Movies_Regex) ausgeführt!-----------
-----------Suchfunktion (WW - Liste: IMDB) gestartet!-----------
Kein Hostname gesetzt. Stoppe Suche für Filme! (IMDB)
-----------Suchfunktion (WW - Liste: IMDB) ausgeführt!-----------
-----------Suchfunktion (WW - Liste: List_ContentAll_Movies) gestartet!-----------
Kein Hostname gesetzt. Stoppe Suche für Filme! (List_ContentAll_Movies)
-----------Suchfunktion (WW - Liste: List_ContentAll_Movies) ausgeführt!-----------
-----------Suchfunktion (WW - Liste: List_ContentAll_Seasons) gestartet!-----------
-----------Suchfunktion (WW - Liste: List_ContentAll_Seasons) ausgeführt!-----------
-----------Suchfunktion (NK - Liste: List_ContentAll_Movies_Regex) gestartet!-----------
Regex deaktiviert. Stoppe Suche für Filme! (List_ContentAll_Movies_Regex)
-----------Suchfunktion (NK - Liste: List_ContentAll_Movies_Regex) ausgeführt!-----------
-----------Suchfunktion (NK - Liste: IMDB) gestartet!-----------
Kein Hostname gesetzt. Stoppe Suche für Filme! (IMDB)
-----------Suchfunktion (NK - Liste: IMDB) ausgeführt!-----------
-----------Suchfunktion (NK - Liste: List_ContentAll_Movies) gestartet!-----------
Kein Hostname gesetzt. Stoppe Suche für Filme! (List_ContentAll_Movies)
-----------Suchfunktion (NK - Liste: List_ContentAll_Movies) ausgeführt!-----------
-----------Suchfunktion (NK - Liste: List_ContentAll_Seasons) gestartet!-----------
-----------Suchfunktion (NK - Liste: List_ContentAll_Seasons) ausgeführt!-----------
-----------Suchfunktion (BY - Liste: List_ContentAll_Movies_Regex) gestartet!-----------
Regex deaktiviert. Stoppe Suche für Filme! (List_ContentAll_Movies_Regex)
-----------Suchfunktion (BY - Liste: List_ContentAll_Movies_Regex) ausgeführt!-----------
-----------Suchfunktion (BY - Liste: IMDB) gestartet!-----------
Kein Hostname gesetzt. Stoppe Suche für Filme! (IMDB)
-----------Suchfunktion (BY - Liste: IMDB) ausgeführt!-----------
-----------Suchfunktion (BY - Liste: List_ContentAll_Movies) gestartet!-----------
Kein Hostname gesetzt. Stoppe Suche für Filme! (List_ContentAll_Movies)
-----------Suchfunktion (BY - Liste: List_ContentAll_Movies) ausgeführt!-----------
-----------Suchfunktion (BY - Liste: List_ContentAll_Seasons) gestartet!-----------
-----------Suchfunktion (BY - Liste: List_ContentAll_Seasons) ausgeführt!-----------
2021-12-14 10:57:32 - Alle Suchfunktion ausgeführt (Dauer: 00:00:07)!
2021-12-14 10:57:32 - Der FeedCrawler-Cache hat 10 HTTP-Requests gespart!
-----------Wartezeit bis zum nächsten Suchlauf: 00:10:00-----------
2021-12-14 10:57:32 - Alle Suchfunktion ausgeführt (Dauer: 00:00:07)! Der FeedCrawler-Cache hat 10 HTTP-Requests gespart!
-----------Wartezeit bis zum nächsten Suchlauf: 00:10:00-----------**

**Comment by DKeppi** [comment]
Bei v11.1.7 direkt 2 Treffer:

**[Episode/RegEx] - Leverage.Redemption.S01E11.DL.GERMAN.WEBRiP.X264-4SJ - [SJ]
[Episode/RegEx] - Leverage.Redemption.S01E10.DL.GERMAN.WEBRiP.X264-4SJ - [SJ]
**

**Comment by rix1337** [comment]
Zur weiteren Analyse braucht's den DEBUG-Log (idealerweise einmal auf v.12.0.1 und auf 11.1.7).
Die INFO-Logs oben reichen nicht aus.

## Weiterhin zwingend erforderlich

- **Genutzte Version** (kein Support für alte Releases) -> v.12.0.0 ist veraltet. Tritt das Verhalten auch in 12.0.1 auf?

- **Wird Python 3.9 oder aktueller genutzt?**

**Comment by DKeppi** [comment]
Das war das DEBUG Log von 12.0.1. - lade es nochmals hoch!
[FeedCrawler_DEBUG.log](https://github.com/rix1337/FeedCrawler/files/7711450/FeedCrawler_DEBUG.log)

Auftreten tut das seit 12.0.0

Verwende den Docker Container, keine Ahnung welches Python da drin ist ;)

db und ini auch anbei (habe User, PW und dergleichen mit xxxxxxxxx anonymisiert) und in der db ist nun natürlich mittlerweile die gefundene Episode durch Version 11.1.7 drinnen
[FeedCrawler.zip](https://github.com/rix1337/FeedCrawler/files/7711459/FeedCrawler.zip)

**Comment by rix1337** [comment]
Hm, also soweit ich den Log sehe findet er ja was:
```2021-12-14 10:55:30,497 - Young.Sheldon.S05E01.DL.GERMAN.WEBRiP.X264-4SJ - Release ignoriert (Gleiche oder bessere Quelle bereits vorhanden)
2021-12-14 10:55:32,664 - Undercover.2019.S03E04.GERMAN.WEBRiP.X264-4SJ - Release ignoriert (Gleiche oder bessere Quelle bereits vorhanden)
2021-12-14 10:55:34,013 - Undercover.2019.S03E03.GERMAN.WEBRiP.X264-4SJ - Release ignoriert (Gleiche oder bessere Quelle bereits vorhanden)
2021-12-14 10:55:34,014 - Undercover.2019.S03E02.GERMAN.WEBRiP.X264-4SJ - Release ignoriert (Gleiche oder bessere Quelle bereits vorhanden)
2021-12-14 10:55:34,015 - Undercover.2019.S03E01.GERMAN.WEBRiP.X264-4SJ - Release ignoriert (Gleiche oder bessere Quelle bereits vorhanden)
2021-12-14 10:55:34,017 - Undercover.2019.S02E01-S02E10.DL.GERMAN.WEBRiP.x264-4SJ - Release ignoriert (Gleiche oder bessere Quelle bereits vorhanden)
2021-12-14 10:55:34,596 - Rick.And.Morty.S05E10.DL.GERMAN.WEBRiP.X264-4SJ - Release ignoriert (Gleiche oder bessere Quelle bereits vorhanden)
2021-12-14 10:55:34,598 - Rick.And.Morty.S05E09.DL.GERMAN.WEBRiP.X264-4SJ - Release ignoriert (Gleiche oder bessere Quelle bereits vorhanden)
2021-12-14 10:55:36,070 - Riverdale.S06E04.DL.GERMAN.WEBRiP.X264-4SJ - Release ignoriert (Gleiche oder bessere Quelle bereits vorhanden)
2021-12-14 10:55:36,075 - Young.Sheldon.S04E18.DL.GERMAN.WEBRiP.X264-4SJ - Release ignoriert (Gleiche oder bessere Quelle bereits vorhanden)
2021-12-14 10:55:36,077 - Young.Sheldon.S04E17.DL.GERMAN.WEBRiP.X264-4SJ - Release ignoriert (Gleiche oder bessere Quelle bereits vorhanden)```

er lädt es nur nicht, weil Gleiche/bessere Quelle schon gefunden wurde..

Ein Log wäre hilfreich (DEBUG) was passiert wenn du v.11.1.7 laufen lässt (vorher die FeedCrawler.db wegwerfen (gerne backup machen) und dann was passiert wenn die 12.0.1 läuft (ebenfalls vorher die DB wegwerfen).

Erwartungshaltung: Beide logs sehen gleich aus

**Comment by DKeppi** [comment]
Beide Logs anbei, habe die db vorab weggeworfen und beide Male diese Suchliste angelegt

**American.Crime.Story.*.WEBRiP.X264-LAW
Die.Simpsons.*.WEBRiP.x264-GERTv
Final.Space.*.480p.AmazonHD.x264-GDR
Leverage.Redemption.*.X264-4SJ
Mr.Inbetween.*.WEBRiP.x264-4SJ
Rick.and.Morty.*.WEBRiP.X264-4SJ
Riverdale.*.WEBRiP.x264-4SJ
The.Walking.Dead.*.WEBRiP.X264-4SJ
Undercover.2019.*.WEBRiP.X264-4SJ
Young.Sheldon.*.WEBRiP.x264-4SJ**

**Comment by rix1337** [comment]
Super, vielen Dank. Ich schaus mir an.

**Comment by DKeppi** [comment]
Danke dir! :)

**Comment by rix1337** [comment]
Gelöst. Danke, war ein fieser Bug. Tritt nur auf, wenn man FX nicht nutzt...

**Comment by DKeppi** [comment]
Danke dir, ich aktualisiere gleich :)
