### ISSUE TITLE
Suchintervall & Suchtiefe verhalten sich eigenartig

### ISSUE THREAD

**Issue by jankete** [rix1337/FeedCrawler#579]
# [FeedCrawler] Fehlermeldung

## Zwingend erforderlich

- **Fehlermeldung aus dem Log** (ggf. DEBUG aktivieren!)
leider keine

- **Genutzte Version** (kein Support für alte Releases)
12.2.8

- **Wird Python 3.9 oder aktueller genutzt?**
Docker-Container

## Fehlerbeschreibung

In den Einstellungen im Abschnitt "FF / SF": Wenn ich das Suchintervall auf 8 einstelle und speichere, springen die Tage bei der Suchtiefe automatisch auf 7. Versuche ich dann z.B. wieder 3 Tage einzutragen, lässt mich der Button zwar speichern, es stehen unmittelbar danach aber wieder 7 Tage drin. Zu besseren Veranschaulichung habe ich via Gitter-PM ein Video geschickt.

**Comment by rix1337** [comment]
https://github.com/rix1337/FeedCrawler/blob/db8f1a72f7303824e186f72c89d023bbb8986e85/feedcrawler/web.py#L437

Da sollte search statt interval stehen
