### ISSUE TITLE
Fehler bei SF

### ISSUE THREAD

**Issue by mx-hero** [rix1337/FeedCrawler#615]
# [FeedCrawler] Fehlermeldung

## Zwingend erforderlich

Log vom Helper:

[AntiGateHandler Entschlüsselung erfolgreich] - ******.German.DD51.Dubbed.DL.720p.AmazonHD.AVC-TVS
[AntiGateHandler] https://filecrypt.co/container/********.html?mirror=0 (Password: ******) wurde innerhalb der letzten Stunde bereits gelöst.
[AntiGateHandler Entschlüsselung erfolgreich] - ******.German.DD51.Dubbed.DL.720p.AmazonHD.AVC-TVS
[AntiGateHandler] https://filecrypt.co/container/********.html?mirror=0 (Password: ******) wurde innerhalb der letzten Stunde bereits gelöst.
[AntiGateHandler Entschlüsselung erfolgreich] - ******.German.DD51.Dubbed.DL.720p.AmazonHD.AVC-TVS
[AntiGateHandler] https://filecrypt.co/container/********.html?mirror=0 (Password: ******) wurde innerhalb der letzten Stunde bereits gelöst.
[AntiGateHandler Entschlüsselung erfolgreich] - ******.German.DD51.Dubbed.DL.720p.AmazonHD.AVC-TVS

Log vom Crawler:

[FeedCrawler Sponsors Helper erfolgreich] - *****.German.DD51.Dubbed.DL.720p.AmazonHD.AVC-TVS
[FeedCrawler Sponsors Helper erfolgreich] - *****.German.DD51.Dubbed.DL.720p.AmazonHD.AVC-TVS
2022-04-26 10:15:15 - Alle Suchläufe ausgeführt (Dauer: 00:15:58)!
2022-04-26 10:15:15 - Die Ombi-Suche lief für: 32 Filme und 12 Serien
-----------Wartezeit bis zum nächsten Suchlauf: 01:08:29-----------
[FeedCrawler Sponsors Helper erfolgreich] - *****.German.DD51.Dubbed.DL.720p.AmazonHD.AVC-TVS
[FeedCrawler Sponsors Helper erfolgreich] - *****.German.DD51.Dubbed.DL.720p.AmazonHD.AVC-TVS
[FeedCrawler Sponsors Helper erfolgreich] - *****.German.DD51.Dubbed.DL.720p.AmazonHD.AVC-TVS
[FeedCrawler Sponsors Helper erfolgreich] - *****.German.DD51.Dubbed.DL.720p.AmazonHD.AVC-TVS
[CAPTCHA zu lösen] - *****.German.DD51.Dubbed.DL.720p.AmazonHD.AVC-TVS

- **Genutzte Version** (kein Support für alte Releases)

14.0.0

## Fehlerbeschreibung

Nach dem erfolgreichen Lösen des Captchas wird der Link vom Helper alle 5 Minuten erneut zum JD hinzugefügt. Offensichtlich befindet er sich in einer Endlosschleife. Diesen Effekt habe ich jedoch nur bei SF. 
Bin mir nicht sicher ob das ein Problem des Helpers oder des Crawlers ist. Der Crawler bekommt vom Helper auch keine Rückmeldung dass es gelöst wurde, steht immer noch rot markiert in der Liste im Crawler, obwohl ich den Download jetzt schon 6 Mal drin habe.
Erst durch löschen des Eintrages im Crawler hört das auf.

**Comment by mx-hero** [comment]
> @mx-hero das Issue-Template wurde nicht befolgt. Schließe dieses Issue automatisch!

? Was hab ich vergessen?

**Comment by rix1337** [comment]
Der Github-Bot prüft die Formulierung "Fehlermeldung aus dem Log"

**Comment by rix1337** [comment]
Duplikat von #614
