### ISSUE TITLE
Endlosschleife und Problem mit SF

### ISSUE THREAD

**Issue by mx-hero** [rix1337/FeedCrawler#622]
# [FeedCrawler] Fehlermeldung

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 01-migrations: executing...
[migrations] started
[migrations] no migrations found
[cont-init.d] 01-migrations: exited 0.
[cont-init.d] 02-tamper-check: executing...
[cont-init.d] 02-tamper-check: exited 0.
[cont-init.d] 10-adduser: executing...
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 90-custom-folders: executing...
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
┌──────────────────────────────────────────────┐
FeedCrawler v.14.0.3 von RiX
https://github.com/rix1337/FeedCrawler
└──────────────────────────────────────────────┘
Nutze das Verzeichnis /config für Einstellungen/Logs
Hostname für SJ: *******
Hostname für DJ: *******
Hostname für SF: *******
Hostname für BY: Nicht gesetzt!
Hostname für FX: *******
Hostname für FF: *******
Hostname für HW: Nicht gesetzt!
Hostname für NK: Nicht gesetzt!
Hostname für WW: *******
Hostname für DD: Nicht gesetzt!
Erfolgreich mit My JDownloader verbunden. Gerätename: JDownloader@unRAID
Der Zugriff auf WW erfolgt nur mit FlareSolverr!
Der Zugriff auf WW mit FlareSolverr funktioniert!
Fehler bei Aufruf von: http://192.168.87.10:5055//api/v1/request?take=999 (<urlopen error [Errno 111] Connection refused>, timeout=60s)

Overseerr API-Key ungültig!
[IMDb] - tt3291150 - Deutscher Titel nicht ermittelbar
[Ombi] - Fehler beim Abruf der IMDb für: tt3291150
[IMDb] - None - Deutscher Titel nicht ermittelbar
[Suche/Serie] - Das.Rad.der.Zeit.SSSSSSS01E02.German.DL.720p.WEB.h264-OHD - SF
[Suche/Serie] - Das.Rad.der.Zeit.SSSSSSS01E03.German.DL.720p.WEB.h264-OHD - SF
[Suche/Serie] - Das.Rad.der.Zeit.SSSSSSS01E04.German.DL.720p.WEB.h264-OHD - SF
[Suche/Serie] - Das.Rad.der.Zeit.SSSSSSS01E05.German.DL.720p.WEB.h264-OHD - SF
[Suche/Serie] - Das.Rad.der.Zeit.SSSSSSS01E06.German.DL.720p.WEB.h264-OHD - SF
Serie/Staffel/Episode: Das Rad der Zeit durch Ombi hinzugefügt.
Serie/Staffel/Episode: Love is Blind After the Altar durch Ombi hinzugefügt.
Serie/Staffel/Episode: Love is Blind After the Altar durch Ombi hinzugefügt.
Fehler bei Aufruf von: https://SJ/serie/search?q=The+Expanse (The read operation timed out, timeout=10s)
Fehler bei Aufruf von: https://SJ/serie/search?q=The+Expanse (The read operation timed out, timeout=10s)
[Suche/Serie] - The.Expanse.SSSSS06E02.German.DL.720p.WEB.h264-OHD - SF
[Suche/Serie] - The.Expanse.SSSSS06E02.German.DL.720p.WEB.h264-OHD - SF
[Suche/Serie] - The.Expanse.SSSSS06E03.German.DL.720p.WEB.h264-OHD - SF
[Suche/Serie] - The.Expanse.SSSSS06E04.German.DL.720p.WEB.h264-OHD - SF
[Suche/Serie] - The.Expanse.SSSSS06E04.German.DL.720p.WEB.h264-OHD - SF
Serie/Staffel/Episode: The Expanse durch Ombi hinzugefügt.
Serie/Staffel/Episode: Harry Potter Hogwarts Tournament of Houses durch Ombi hinzugefügt.
Fehler bei Aufruf von: https://SJ/serie/search?q=Pam+&amp+Tommy (The read operation timed out, timeout=10s)
Traceback (most recent call last):
File "/usr/lib/python3.9/site-packages/feedcrawler/crawler.py", line 119, in crawler
ombi_results = ombi(request_management_first_run)
File "/usr/lib/python3.9/site-packages/feedcrawler/request_management/ombi.py", line 144, in ombi
added_episode = feedcrawler.search.shared.content_shows.download(
File "/usr/lib/python3.9/site-packages/feedcrawler/search/shared/content_shows.py", line 111, in download
season = re.findall(r"(Staffel .*)", release.text.strip())[0].replace("Staffel ", "S")
IndexError: list index out of range
Fehler bei Aufruf von: https://SJ/api/releases/latest/0 (The read operation timed out, timeout=10s)
Der Zugriff auf SJ ist für die aktuelle IP gesperrt!
Der Zugriff auf SJ ist mit FlareSolverr gesperrt!
Der Zugriff auf SJ ist mit FlareSolverr + Proxy gesperrt!
Der Zugriff auf SJ ist mit FlareSolverr + Proxy gesperrt!
Der Zugriff auf WW erfolgt nur mit FlareSolverr!
Der Zugriff auf WW mit FlareSolverr funktioniert!
Fehler bei Aufruf von: http://192.168.87.10:5055//api/v1/request?take=999 (<urlopen error [Errno 111] Connection refused>, timeout=60s)

Overseerr API-Key ungültig!
[IMDb] - tt3291150 - Deutscher Titel nicht ermittelbar
[Ombi] - Fehler beim Abruf der IMDb für: tt3291150
[IMDb] - None - Deutscher Titel nicht ermittelbar
[Suche/Serie] - Das.Rad.der.Zeit.SSSSSSS01E02.German.DL.720p.WEB.h264-OHD - SF
[Suche/Serie] - Das.Rad.der.Zeit.SSSSSSS01E03.German.DL.720p.WEB.h264-OHD - SF
[Suche/Serie] - Das.Rad.der.Zeit.SSSSSSS01E04.German.DL.720p.WEB.h264-OHD - SF
[Suche/Serie] - Das.Rad.der.Zeit.SSSSSSS01E05.German.DL.720p.WEB.h264-OHD - SF
[Suche/Serie] - Das.Rad.der.Zeit.SSSSSSS01E06.German.DL.720p.WEB.h264-OHD - SF
Serie/Staffel/Episode: Das Rad der Zeit durch Ombi hinzugefügt.
Serie/Staffel/Episode: Love is Blind After the Altar durch Ombi hinzugefügt.
Serie/Staffel/Episode: Love is Blind After the Altar durch Ombi hinzugefügt.
[Suche/Serie] - The.Expanse.SSSSS06E02.German.DL.720p.WEB.h264-OHD - SF
[Suche/Serie] - The.Expanse.SSSSS06E02.German.DL.720p.WEB.h264-OHD - SF
[Suche/Serie] - The.Expanse.SSSSS06E03.German.DL.720p.WEB.h264-OHD - SF
[Suche/Serie] - The.Expanse.SSSSS06E04.German.DL.720p.WEB.h264-OHD - SF
Serie/Staffel/Episode: The Expanse durch Ombi hinzugefügt.
Serie/Staffel/Episode: Harry Potter Hogwarts Tournament of Houses durch Ombi hinzugefügt.
Traceback (most recent call last):
File "/usr/lib/python3.9/site-packages/feedcrawler/crawler.py", line 119, in crawler
ombi_results = ombi(request_management_first_run)
File "/usr/lib/python3.9/site-packages/feedcrawler/request_management/ombi.py", line 144, in ombi
added_episode = feedcrawler.search.shared.content_shows.download(
File "/usr/lib/python3.9/site-packages/feedcrawler/search/shared/content_shows.py", line 111, in download
season = re.findall(r"(Staffel .*)", release.text.strip())[0].replace("Staffel ", "S")
IndexError: list index out of range
Fehler bei Aufruf von: https://SJ/api/releases/latest/0 (The read operation timed out, timeout=10s)
Der Zugriff auf SJ ist für die aktuelle IP gesperrt!
Fehler bei Aufruf von: https://SJ/api/releases/latest/0 (The read operation timed out, timeout=10s)
Der Zugriff auf SJ ist für die aktuelle IP gesperrt!
Der Zugriff auf SJ ist mit FlareSolverr gesperrt!
Der Zugriff auf SJ ist mit FlareSolverr + Proxy gesperrt!
Fehler bei Aufruf von: https://DJ/api/releases/latest/0 (The read operation timed out, timeout=10s)
Der Zugriff auf DJ ist für die aktuelle IP gesperrt!
Der Zugriff auf DJ ist mit FlareSolverr gesperrt!
Der Zugriff auf DJ mit FlareSolverr + Proxy funktioniert!
Der Zugriff auf WW erfolgt nur mit FlareSolverr!
Der Zugriff auf WW mit FlareSolverr funktioniert!
Fehler bei Aufruf von: http://192.168.87.10:5055//api/v1/request?take=999 (<urlopen error [Errno 111] Connection refused>, timeout=60s)

Overseerr API-Key ungültig!
[IMDb] - tt3291150 - Deutscher Titel nicht ermittelbar
[Ombi] - Fehler beim Abruf der IMDb für: tt3291150
[IMDb] - None - Deutscher Titel nicht ermittelbar
[IMDb] - None - Deutscher Titel nicht ermittelbar
[Suche/Serie] - Das.Rad.der.Zeit.SSSSSSS01E02.German.DL.720p.WEB.h264-OHD - SF
[Suche/Serie] - Das.Rad.der.Zeit.SSSSSSS01E03.German.DL.720p.WEB.h264-OHD - SF
[Suche/Serie] - Das.Rad.der.Zeit.SSSSSSS01E03.German.DL.720p.WEB.h264-OHD - SF
[Suche/Serie] - Das.Rad.der.Zeit.SSSSSSS01E04.German.DL.720p.WEB.h264-OHD - SF
[Suche/Serie] - Das.Rad.der.Zeit.SSSSSSS01E04.German.DL.720p.WEB.h264-OHD - SF
[Suche/Serie] - Das.Rad.der.Zeit.SSSSSSS01E05.German.DL.720p.WEB.h264-OHD - SF
[Suche/Serie] - Das.Rad.der.Zeit.SSSSSSS01E06.German.DL.720p.WEB.h264-OHD - SF
Serie/Staffel/Episode: Das Rad der Zeit durch Ombi hinzugefügt.
Serie/Staffel/Episode: Love is Blind After the Altar durch Ombi hinzugefügt.
Serie/Staffel/Episode: Love is Blind After the Altar durch Ombi hinzugefügt.
[Suche/Serie] - The.Expanse.SSSSS06E02.German.DL.720p.WEB.h264-OHD - SF
[Suche/Serie] - The.Expanse.SSSSS06E02.German.DL.720p.WEB.h264-OHD - SF
[Suche/Serie] - The.Expanse.SSSSS06E03.German.DL.720p.WEB.h264-OHD - SF
[Suche/Serie] - The.Expanse.SSSSS06E04.German.DL.720p.WEB.h264-OHD - SF
Serie/Staffel/Episode: The Expanse durch Ombi hinzugefügt.
Serie/Staffel/Episode: Harry Potter Hogwarts Tournament of Houses durch Ombi hinzugefügt.
usw....

**Ideen/Feature Requests** gehören in die [Discussions](https://github.com/rix1337/FeedCrawler/discussions/).

Für **Rückfragen** und Allgemeines gibt es den [Chat auf gitter](https://gitter.im/FeedCrawler/community).

## Zwingend erforderlich

- **Fehlermeldung aus dem Log** (ggf. DEBUG aktivieren!)

- **Genutzte Version** (kein Support für alte Releases)
14.0.3

- **Wird Python 3.9 oder aktueller genutzt?**
Docker

## Fehlerbeschreibung

Er scheint in einer Endlosschleife zu sein, schickt mir alle 3 min die gleichen Notifications und das Log wiederholt sich permanent ohne zum Ende zu kommen.

Außerdem scheint er was zu finden (oder auch nicht) bei SF... allerdings immer mit SSSSSSSSSS davor. Diese "Ergebnisse" tauchen dann auch im Log vom JD auf, allerdings nur in der Übersicht im Crawler, nicht im JD selbst und diese lassen sich auch nicht löschen, da kommt immer der Fehler "Konnte nicht gelöscht werden". (siehe Screenshot)

## Weder FeedCrawler noch der Autor benennen oder befürworten spezifische Hostnamen.
Fragen hierzu werden kommentarlos geschlossen!

Spezifische, vom Anwender in der _FeedCrawler.ini_ unter _[Hostnames]_ eingetragene Hostnamen, sind unkenntlich zu machen.

![Screenshot 2022-05-01 215437](https://user-images.githubusercontent.com/6332374/166162390-a97d5a6c-40c2-46a7-9629-1e9859c72c5e.png)

**Comment by rix1337** [comment]
Danke für das issue. Waren mehrere Punkte, die behoben sein sollten
