### ISSUE TITLE
Crawler kann den JD2 nicht mehr erreichen

### ISSUE THREAD

**Issue by feuerwasser85** [rix1337/FeedCrawler#635]
# Fehlermeldung im Crawler: "Konnte JDownloader nicht erreichen!"

## Fehlermeldung aus dem Log
```Traceback (most recent call last): File "/usr/lib/python3.9/site-packages/feedcrawler/watchdog.py", line 36, in crawldog myjd_packages = get_info() File "/usr/lib/python3.9/site-packages/feedcrawler/myjd.py", line 354, in get_info packages_in_downloader = get_packages_in_downloader() File "/usr/lib/python3.9/site-packages/feedcrawler/myjd.py", line 138, in get_packages_in_downloader packages_by_type = check_packages_types(links, packages) File "/usr/lib/python3.9/site-packages/feedcrawler/myjd.py", line 194, in check_packages_types size = readable_size(size) File "/usr/lib/python3.9/site-packages/feedcrawler/common.py", line 374, in readable_size size_value = round(float(re.sub('[^0-9,.]', '', size)), 2) File "/usr/lib/python3.9/re.py", line 210, in sub return _compile(pattern, flags).sub(repl, string, count) TypeError: expected string or bytes-like object```
## Genutzte Version

Docker Imgage 14.2.2 hosted auf Synology DS920+. JD2 lokal, verbunden mit myJD Cloud

## Fehlerbeschreibung

Seit der neuesten 14.2.2 kann der Feedcrawler den JD nicht mehr erreichen. Der JD läuft, ich kann ihn auch unter myJD erreichen. In einer bash im Feedcrawler Docker kann ich die myJD.org pingen, ein curl steht leider nicht zur Verfügung.
Mein Aufbau: Feedcrawler als Docker Container auf einer DS920+, JD2 als lokales Paket, nicht unter Docker. Bekomme im FeedCrwaler die Meldung "Konnte JDownloader nicht erreichen!".

**Comment by rix1337** [comment]
Behoben in 14.2.3

**Comment by feuerwasser85** [comment]
Wahnsinnsgeschwindigkeit. Denke ich hab länger gebraucht um das Ticket aufzumachen. Danke!

**Comment by rix1337** [comment]
Hehe, der Fehler war durch den Log recht schnell gefunden ;)
Viel Spaß damit
