### ISSUE TITLE
Is this suitable for music?

### ISSUE THREAD

**Issue by dreadedhamish** [rix1337/FeedCrawler#654]
I've set up FeedCrawler, added sites, and everything seems to be working fine (added sites are added, some are fine, a few with SSL errors etc...)

Searches however don't work - as as I've dug deeper into the app it looks like it is created and usable just for video?

**Comment by rix1337** [comment]
Hey @dreadedhamish 
And thanks for taking interest in this project.

FeedCrawler is not internationalized and I lack the resources to implement this.

Only German users are able to use this project.

Regarding your question: music is out of scope.
