### ISSUE TITLE
Database locked

### ISSUE THREAD

**Issue by DKeppi** [rix1337/FeedCrawler#655]
Hallo,

habe bemerkt, dass mein Feedcrawler 15.0.3 (Docker) schon des längeren nichts mehr crawlt.
Daher mal den DEBUG aktiviert und eine von Grund auf neue Installation gemacht, also neues Image, neue ini und neue db (alte davor natürlich gesichert)

Folgender Output kommt im DEBUG Mode:

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.9/site-packages/feedcrawler/jobs/package_watcher.py", line 29, in watch_packages
    shared_state.set_globals(global_variables)
  File "/usr/lib/python3.9/site-packages/feedcrawler/providers/shared_state.py", line 50, in set_globals
    set_device(global_variables["device"])
  File "/usr/lib/python3.9/site-packages/feedcrawler/providers/shared_state.py", line 91, in set_device
    FeedDb('cached_internals').store("device", codecs.encode(pickle.dumps(device), "base64").decode())
  File "/usr/lib/python3.9/site-packages/feedcrawler/providers/sqlite_database.py", line 20, in __init__
    if not self._conn.execute(
sqlite3.OperationalError: database is locked 
```

**Comment by DKeppi** [comment]
Hab den Feedcrawler nun nochmals komplett neu augesetzt und siehe da, der Crawl funktioniert wieder.
Den Fehler solltest du dir aber mal ansehen, denn der bleibt im Log... DANKE!

**Comment by rix1337** [comment]
Der Fehler heißt einfach nur, dass irgendein Prozess die Datenbank blockiert. Wie startest / betreibst du den FeedCrawler denn?

**Comment by DKeppi** [comment]
Mittels Docker Container auf einer Synology

**Comment by rix1337** [comment]
@DKeppi  ich konnte das Verhalten bisher nicht nachstellen.

Vorschlag zur Güte: Den HTML-Cache kann ich per Startparameter oder Option deaktivierbar machen.
Dann läuft der Crawler etwas langsamer - aber der Lock tritt vermutlich nicht mehr auf.

**Comment by DKeppi** [comment]
Schade, aber dein Vorschlag wäre einen Versuch wert!
Danke 😎

**Comment by rix1337** [comment]
Version 15.0.4 gibt ab jetzt eine Debug-Meldung heraus, wenn eine Datenbankverbindung auf Fehler läuft.
Danach wird maximal 15 Sekunden versucht, die selbe Verbindung nochmals aufzubauen.

Klappt das nicht, wird die Fehlermeldung in die normale Konsole ausgegeben.

Das hilft hoffentlich bei der Problemeingrenzung, falls das Verhalten weiterhin auftritt.
