### ISSUE TITLE
Absturz durch myjd_api.TokenExpiredException

### ISSUE THREAD

**Issue by 9Mad-Max5** [rix1337/FeedCrawler#676]
# [FeedCrawler] Fehlermeldung

## Zwingend erforderlich

- **Fehlermeldung aus dem Log**  siehe unten

- **Genutzte Version** docker

## Fehlerbeschreibung

Nach einer Weile laufen kann es vorkommen, dass die unten aufgeführte Fehlermeldung direkt im Log erscheint.
Könnte auch durch einen disconnect über den Zwangsneustart von jd kommen.

Crawler Neustart löst das Problem meistens.

## Weder FeedCrawler noch der Autor benennen oder befürworten spezifische Hostnamen.
Fragen hierzu werden kommentarlos geschlossen!

Spezifische, vom Anwender in der _FeedCrawler.ini_ unter _[Hostnames]_ eingetragene Hostnamen, sind unkenntlich zu machen.
`Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.9/site-packages/feedcrawler/jobs/feed_search.py", line 245, in crawler
    current_donation_banner_setting = shared_state.device.config.get(
  File "/usr/lib/python3.9/site-packages/feedcrawler/external_tools/myjd_api.py", line 191, in get
    resp = self.device.action(self.url + "/get", params)
  File "/usr/lib/python3.9/site-packages/feedcrawler/external_tools/myjd_api.py", line 862, in action
    response = self.myjd.request_api(path, http_action, params,
  File "/usr/lib/python3.9/site-packages/feedcrawler/external_tools/myjd_api.py", line 1202, in request_api
    raise TokenExpiredException
feedcrawler.external_tools.myjd_api.TokenExpiredException`

**Comment by rix1337** [comment]
Das kommt durch den Neustart und ist völlig normal.

Solange der crawler sich danach wieder beim jdownloader einwählen kann, ist nichts zu beheben/tun.

**Comment by 9Mad-Max5** [comment]
Für gewöhnlich kommt es dazu nicht nach meinem Verständnis von Python breaked das ganze script hier solange es nicht gefangen wird.
Demnach würde ein
try:
except: 
  pass
Etwa helfen.

**Comment by rix1337** [comment]
Den Except gibt es schon. Deine Fehlermeldung wird hier ausgelöst: `/usr/lib/python3.9/site-packages/feedcrawler/jobs/feed_search.py", line 245`
Die Meldung kommt also aus der allgemeinen Feedsuche. Wenn dort eine Exception geschmissen wird, landet diese immer auf der Konsole (falls etwas grob schief gelaufen ist, weiß man dann, warum):
![grafik](https://user-images.githubusercontent.com/9930448/211153489-b3b0996a-a975-46dd-a311-bb0dc9b7d9ac.png)

Nach 10 Sekunden beginnt die Feedsuche regulär von vorn.

Wenn die Exception auftritt, weil der JDownloader im Updateprozess hing, ist die Meldung berechtigt und wie gesagt kein Problem.

Der FeedCrawler sollte sich im nächsten Lauf wieder mit dem JDownloader verbinden, sofern der wieder da und mit My JDownloader verbunden ist.

**Comment by rix1337** [comment]
Danke @9Mad-Max5  trotzdem für die Meldung. Genau für solche Fälle schmeißt die Feedsuche die Exception ins Log. Wenn dort etwas auftaucht, muss das in jedem Fall genauer angeschaut werden.

Nur in diesem speziellen Fall ist die Ursache nachvollziehbar - und es gibt nichts zu tun.

**Comment by 9Mad-Max5** [comment]
@rix1337 Ich denke das Problem liegt daran, dass mein JD in der Nacht neu startet und durch die lange Zeit bis der nächste Suchlauf startet der Token ausgelaufen ist.
Ich schaue mal morgen früh wies, schaut aber fürchte nicht das es klappt und er wie in der Vergangenheit dann den Timer einfach stecken bleibt.

**Comment by rix1337** [comment]
Die myjdapi handelt wie gesagt einen neuen Token aus, sobald mal was schief läuft.
