### ISSUE TITLE
Fehlendes Icon FeedCrawler Unraid. incl. Bugfix.

### ISSUE THREAD

**Issue by kroeberd** [rix1337/FeedCrawler#693]
# [FeedCrawler] Fehlermeldung

Feb  5 10:46:20 WebserverNAS root: FeedCrawler: Could not download icon https://raw.githubusercontent.com/rix1337/FeedCrawler/master/feedcrawler/web/img/favicon.ico

Icon kann in Unraid nicht geladen werden

## Zwingend erforderlich

- Feb  5 10:46:20 WebserverNAS root: FeedCrawler: Could not download icon https://raw.githubusercontent.com/rix1337/FeedCrawler/master/feedcrawler/web/img/favicon.ico

- Unraid 6.11.0

- **Wird Python 3.8 oder aktueller genutzt?** Ja

## Fehlerbeschreibung

Icon kann in Unraid nicht geladen werden

Lösung:

Alten Icon-Pfad durch "https://raw.githubusercontent.com/rix1337/FeedCrawler/main/feedcrawler/web_interface/vuejs_frontend/public/favicon.ico" ersetzen.

**Comment by rix1337** [comment]
@kroeberd die unRAID config ist bereits auf korrektem stand:
https://github.com/rix1337/docker-templates/blob/081b7a821cf52f855ac48573c4a160da456700b3/rix1337/feedcrawler.xml#L20

Du hast möglicherweise eine alte template version installiert?
Scheinbar updated unRAID das template nach dem Setup nicht mehr.
