### ISSUE TITLE
Filterliste wird ignoriert

### ISSUE THREAD

**Issue by jankete** [rix1337/FeedCrawler#697]
### Hast du die README gelesen?

- [X] Ich habe die README gelesen

### Gibt es bereits ein Issue für das Problembild?

- [X] Ich habe ältere, offene und geschlossene Issues überprüft

### Hast du die Discussions überprüft?

- [X] Ich habe die Diskussionen gelesen

### Enthält die Problembeschreibung einen oder mehrere Hostnamen?

- [X] Nein, ich habe keine Hostnamen in der Problembeschreibung hinterlegt.

### Laufzeitumgebung

```markdown
- FeedCrawler Version: 16.4.0
- Letzte funktionierende FeedCrawler-Version: unbekannt
- Docker: ja
- FlareSolverr: ja
- Proxy: ja
```

### Beschreibung

Ich betreibe den Crawler mit folgender Filterliste, die bestimmte Releases ausschließen sollte.

`cam,subbed,xvid,dvdr,untouched,remux,avc,pal,md,ac3md,mic,xxx,ld,ac3ld,dubbed,ts`

Dennoch werden Releases mit "LD" oder auch "TS" (oder sogar beidem) gefunden und geladen. Beispiel siehe unten.

Die Einstellung "1080p-HEVC bevorzugen" ist zwar gesetzt, sollte aber hier keinen Einfluss haben, da es sich nicht um ein x265 Release und auch nicht um eine Retail-Version handelt.

### Fehlermeldungen aus dem Log

```text
2023-02-12T15:21:00.556406365Z [Suche/Film] - Knock.At.The.Cabin.2023.TS.LD.German.1080p.x264-PsO - [NX] - 3.51 GB - https://***.**/release/knock-at-the-cabin-2023-ts-ld-german-1080p-x264-pso-ryjTKkHor5r
2023-02-12T15:21:59.143452386Z [CAPTCHA gelöst] - Knock.At.The.Cabin.2023.TS.LD.German.1080p.x264-PsO
```

**Comment by rix1337** [comment]
![grafik](https://user-images.githubusercontent.com/9930448/219652560-c3187d1d-6c36-48be-b0c2-b29ae358409a.png)

Die Hauptaufgabe der Suchfunktion ist es, überhaupt etwas zu finden. Daher wird, wenn nichts anderes verfügbar ist, im letzten Schritt die Auflösung und die Filterliste ignoriert.

**Comment by jankete** [comment]
Der Hinweis/Screenshot betrifft ja die (manuelle) Suche. Für den normalen (automatischen) Crawl gilt das auch?

**Comment by rix1337** [comment]
Die Suchfunktion ist immer die selbe. Egal ob im Webinterface gestartet, oder per Ombi/Overseer/Plex Watchlist.

**Comment by jankete** [comment]
Alles klar. Kann ich mir für zukünftige Versionen wünschen, dass ich die Filterliste forcieren kann? Ich will einfach keine MD Releases haben 😁

**Comment by rix1337** [comment]
Naheliegender Wunsch. Haus Mal in die diskussionen
