### ISSUE TITLE
Helper - AntiGateHandler - Proxy funktioniert nicht

### ISSUE THREAD

**Issue by mx-hero** [rix1337/FeedCrawler#699]
### Hast du die README gelesen?

- [X] Ich habe die README gelesen

### Gibt es bereits ein Issue für das Problembild?

- [X] Ich habe ältere, offene und geschlossene Issues überprüft

### Hast du die Discussions überprüft?

- [X] Ich habe die Diskussionen gelesen

### Enthält die Problembeschreibung einen oder mehrere Hostnamen?

- [X] Nein, ich habe keine Hostnamen in der Problembeschreibung hinterlegt.

### Laufzeitumgebung

```markdown
- FeedCrawler Version: 16.4.0
- Letzte funktionierende FeedCrawler-Version:
- Betriebssystem: unraid
- Docker: ja
- FlareSolverr: ja
- Proxy: ja
```

### Beschreibung

Ich stelle seit mehreren Wochen fest dass der Helper es nicht mehr schafft Captchas zu lösen, bin leider jetzt erst dazu gekommen mich damit zu beschäftigen.
Helper ist up2date: Version 8.0.1
Port ist freigegeben, sämtliche API´s und IP´s sind korrekt.

### Fehlermeldungen aus dem Log

```text
┌──────────────────────────────────────────────────┐
  Click'n'Load2FeedCrawler von RiX
  https://github.com/rix1337/ClickNLoad2FeedCrawler
└──────────────────────────────────────────────────┘
Nutze NodeJS 12.22.9 zum Parsen von JavaScript
Nutze OpenSSL 3.0.2 15 Mar 2022 zum Entschlüsseln der Links
Nutze FeedCrawler 16.4.0 zur Übergabe der Links an My JDownloader
Click'n'Load ist verfügbar unter http://127.0.0.1:9666 und http://172.17.0.6:9666
[FeedCrawler Sponsors Helper] FeedCrawler available! Starting AntiGateHandler...
[AntiGateHandler] Version 4.0.1 by RiX
[AntiGateHandler] feedcrawler_url=http://192.168.87.10:9090
[AntiGateHandler] anti_captcha_key=****************
[AntiGateHandler] custom_hoster=*******
[AntiGateHandler] proxy_folder=/config/
[AntiGateHandler] v.4.0.1
[AntiGateHandler] Creating HTTP proxy at xx.xx.xxx.x:33333 (User: ************* Pass: *********
[FeedCrawler Sponsors Helper] Waiting for AntiGateHandler to be available...
[FeedCrawler Sponsors Helper] FeedCrawler available! Starting Chrome (Version 110)...
[FeedCrawler Sponsors Helper] Version 8.0.1 by RiX

[AntiGateHandler] Proxy was created but does not work!
[AntiGateHandler] to_decrypt - Error: (400, 'Entschlüsselung gescheitert!')
```

**Comment by rix1337** [comment]
`Proxy was created but does not work!` kann an 3 verschiedenen Problemen liegen

1. https://api.ipify.org ist von deiner IP aus nicht erreichbar oder offline
2. https://ident.me ist von deiner IP aus nicht erreichbar oder offline
3. TCP-Port 33333 ist (warum auch immer) nicht extern erreichbar

Die ersten beiden Punkte kannst du im Browser testen.
Den dritten Punkt, indem du bspw. Firefox die Proxy-Informationen aus
`[AntiGateHandler] Creating HTTP proxy at`
fütterst https://praxistipps.chip.de/firefox-proxy-einstellungen-aendern_27818
Wenn du mit diesen Einstellungen Zugriff auf `https://api.ipify.org` oder `https://ident.me` hast, sollte das Problem NICHT auftreten.

**Comment by rix1337** [comment]
Wird ggf. mit neuen Infos wieder geöffnet.

**Comment by mx-hero** [comment]
Habe das jetzt mal versucht etwas genauer zu prüfen.
Der normale Aufruf der Seiten funktioniert. Mit den geänderten Proxyeinstellungen funktioniert es nicht.
Habe mal einen online Proxy check gemacht und der helper reagiert im Log. Heißt für mich, der Port ist offen und wird sauber durchgeleitet.

[AntiGateHandler] Creating HTTP proxy at xx.xx.xx.xxx:33333 (User: ****** Pass: ******
[FeedCrawler Sponsors Helper] FeedCrawler available! Starting Chrome (Version 110)...
[FeedCrawler Sponsors Helper] Version 8.0.2 by RiX
2023-02-20 16:41:01,969 - pid:114 [I] handler.handle_data:179 - HttpProtocolException: ProxyAuthenticationFailed
2023-02-20 16:41:01,970 - pid:114 [I] server.access_log:384 - 109.248.200.183:46375 - GET None:None/testpage.php?js&rand=26353076 - None None - 0 bytes - 0.71ms
2023-02-20 16:41:02,143 - pid:111 [I] handler.handle_data:179 - HttpProtocolException: HttpRequestRejected b'w3.justchecker.info not on whitelist'
2023-02-20 16:41:02,143 - pid:111 [I] server.access_log:384 - 109.248.200.183:46376 - CONNECT None:None - 0 bytes - 0.92ms

**Comment by rix1337** [comment]
@mx-hero stimmt. in der nächsten Helper Version wird der konkrete Fehler aus dem Proxy Test mit ausgespuckt, dann wissen wir mehr.

**Comment by rix1337** [comment]
@mx-hero aktualisier bitte den Helper auf Version 9.0.0 und füg die ausführlichere Fehlermeldung hier ein.

**Comment by mx-hero** [comment]
Hier das Log:

[AntiGateHandler] Version 5.0.0 by RiX
[AntiGateHandler] feedcrawler_url=http://192.168.87.10:9090
[AntiGateHandler] anti_captcha_key=49b01ddcc7b84d6ac7fd770442ac296d
[AntiGateHandler] custom_hoster=1fichier
[AntiGateHandler] proxy_folder=/config/
[AntiGateHandler] v.5.0.0
[AntiGateHandler] Creating HTTP proxy at xx.xx.xx.xx:33333 (User: ******* Pass: *****
[FeedCrawler Sponsors Helper] FeedCrawler available! Starting Chrome (Version 110)...
[FeedCrawler Sponsors Helper] Version 9.0.0 by RiX
[AntiGateHandler] Decrypting https://filecrypt.**/*****/****.html (Password: *****)
[AntiGateHandler] Proxy was created but does not work: HTTPSConnectionPool(host='ident.me', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x151b69381b10>, 'Connection to xx.xx.xx.xx timed out. (connect timeout=None)'))
[AntiGateHandler] to_decrypt - Error: (400, 'Entschlüsselung gescheitert!')

Er sagt Timeout.... kann mir das nicht erklären...

**Comment by rix1337** [comment]
Okay, es liegt irgendwie/irgendwo am Netzwerk.

Schau bitte nochmal, was passiert wenn du mit den aktuellen Proxy-Daten per Firefox auf ident.me zugreifst.

Bitte hinterleg hier Screenshots:

1. Von den Proxy-Einstellungen im Browser vor dem Test
2. Von dem Seitenaufruf von https://api.ipify.org/ mit den Proxy-Einstellungen im Browser
3. Von dem Seitenaufruf von https://ident.me/ mit den Proxy-Einstellungen im Browser
4. Von dem Log des Sponsors Helper NACH 1., 2. und 3.

**Comment by rix1337** [comment]
@mx-hero  ich mach hier mit mehr Infos gern wieder auf.

**Comment by rix1337** [comment]
@PlanetDyna
Du nutzt laut deinem Issue-Duplikat eine alte FeedCrawler-Version. Stell als erstes sicher, dass du diesen und den Helper auf aktuellem Stand hälst.

Danach befolge die hier beschriebenen Schritte um eine qualifizierte Problembeschreibung zu geben

**Comment by PlanetDyna** [comment]
Vielen Dank, rix1337.

Werde ich machen. Beide Tools sind jetzt geupdated. Es erscheint jetzt folgende Fehlermeldung:

```
[AntiGateHandler] Proxy was created but does not work: HTTPSConnectionPool(host='ident.me', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x15433387e4a0>: Failed to establish a new connection: [Errno 113] No route to host')))
[AntiGateHandler] to_decrypt - Error: cannot unpack non-iterable bool object 
```

**Comment by rix1337** [comment]
@PlanetDyna  was ist das Ergebnis (Screenshots) wenn du [https://github.com/rix1337/FeedCrawler/issues/699#issuecomment-1434548800 befolgst?
](https://github.com/rix1337/FeedCrawler/issues/699#issuecomment-1438217526) befolgst?

**Comment by PlanetDyna** [comment]
Via Firefox habe ich folgende Einstellungen vorgenommen:

https://imgur.com/Hbxi9US

Unkenntliche IP: IP aus dem Log des FeedCrawler-Helper.
Mit diesen Einstellungen kann ich beide Domains nicht aufrufen und es erscheint jeweils kein Eintrag im Log des Helper.
Ohne die Proxy-Settings bekomme ich beim Aufruf beider Seiten die IP des Server ausgegeben.

**Comment by rix1337** [comment]
Es fehlen Screenshots:

- Von dem Seitenaufruf von https://api.ipify.org/ mit den Proxy-Einstellungen im Browser
- Von dem Seitenaufruf von https://ident.me/ mit den Proxy-Einstellungen im Browser
- Von dem Log des Sponsors Helper NACH 1., 2. und 3.

**Comment by rix1337** [comment]
"beide Domains nicht aufrufen und es erscheint jeweils kein Eintrag im Log des Helper" bedeutet, dass dein firefox den helper offenbar überhaupt nicht erreicht. Funktioniert der Aufruf von Google.com etc.?

Läuft bei dir SICHER die neueste Version vom Helper (9.0.2)?

**Comment by rix1337** [comment]
Es fehlen nach wie vor die notwendigen Details um dieses Issue zu bearbeiten.

Bitte neues Issue aufmachen, mit den hier angeforderten Screenshots:
https://github.com/rix1337/FeedCrawler/issues/699#issuecomment-1438217526

**Comment by rix1337** [comment]
@mx-hero hat per Discord mitgeteilt, dass vermutlich der Proxy-Aufruf über die externe IP-Adresse zu Problemen führt.
Ab dem nächsten Release wird stattdessen die lokale Adresse des Sponsors Helpers übernommen und für den Proxy-Aufruf verwendet.
