### ISSUE TITLE
NX-Web-Suche Filtert Auflösung nicht korrekt

### ISSUE THREAD

**Issue by kroeberd** [rix1337/FeedCrawler#708]
### Hast du die README gelesen?

- [X] Ich habe die README gelesen

### Gibt es bereits ein Issue für das Problembild?

- [X] Ich habe ältere, offene und geschlossene Issues überprüft

### Hast du die Discussions überprüft?

- [X] Ich habe die Diskussionen gelesen

### Enthält die Problembeschreibung einen oder mehrere Hostnamen?

- [X] Nein, ich habe keine Hostnamen in der Problembeschreibung hinterlegt.

### Laufzeitumgebung

```markdown
- FeedCrawler Version: v.16.4.5 
- Letzte funktionierende FeedCrawler-Version: v.16.4.5
- Betriebssystem: Unraid 6.11.5
- Docker: ja
- FlareSolverr: ja
- Proxy: nein
```

### Beschreibung

Bei der Suche werden auch HDs angezeigt, statt wie gewünscht nur SD.

Die Config:
[Hostnames]
fx = 
sf = 
dw = 
hw = 
ff = 
by = 
nk = 
nx = XXX
ww = 
sj = 
dj = 
dd = 

[SponsorsHelper]
max_attempts = 2
hide_donation_banner = True

[FeedCrawler]
auth_user = 
auth_hash = 
myjd_user = XXX
myjd_pass = XXX
myjd_device = JDownloader_automation
myjd_auto_update = True
port = 9090
prefix = 
interval = 30
flaresolverr = http://192.168.178.XXX:8191
flaresolverr_proxy = 
english = False
surround = False
one_mirror_policy = True
packages_per_myjd_page = 30
force_ignore_in_web_search = False

[Hosters]
ddl = True
rapidgator = True
1fichier = False
turbobit = False
uploaded = False
zippyshare = False
filefactory = False
uptobox = False
filer = False
nitroflare = False
k2s = True
katfile = False
ironfiles = False
oboom = False

[Notifications]
telegram = 
pushbullet = 
pushover = 
homeassistant = 
discord = XXX

[Plex]
url = 
api = 
client_id = 
pin_code = 
pin_id = 

[Ombi]
url = http://192.168.178.XXX:5000
api = XXX

[Overseerr]
url = 
api = 

[Crawljobs]
autostart = True
subdir = True

[ContentAll]
quality = 480p
search = 10
ignore = cam,ts
regex = False
cutoff = True
enforcedl = False
crawlseasons = True
seasonsquality = 480p
seasonpacks = True
seasonssource = hdtv|hdtvrip|tvrip|web|web-dl|webrip|webhd|netflix*|amazon*|itunes*|bluray|bd|bdrip
imdbyear = 1900
imdb = 1.0
hevc_retail = False
retail_only = False
hoster_fallback = True

[ContentShows]
quality = 480p
rejectlist = 
regex = True
hevc_retail = False
retail_only = False
hoster_fallback = True

[CustomDJ]
quality = 1080p
rejectlist = xvid,subbed,hdtv
regex = False
hoster_fallback = False

[CustomDD]
hoster_fallback = False

[CustomF]
search = 3

[CustomJF]
wait_time = 12

### Fehlermeldungen aus dem Log

```text
[migrations] started
[migrations] no migrations found
[custom-init] No custom files found, skipping...
[ls.io-init] done.
┌──────────────────────────────────────────────┐
  FeedCrawler v.16.4.5 von RiX
  https://github.com/rix1337/FeedCrawler
└──────────────────────────────────────────────┘
Nutze das Verzeichnis /config für Einstellungen/Logs
Hostname für FX: Nicht gesetzt!
Hostname für SF: Nicht gesetzt!
Hostname für DW: Nicht gesetzt!
Hostname für HW: Nicht gesetzt!
Hostname für FF: Nicht gesetzt!
Hostname für BY: Nicht gesetzt!
Hostname für NK: Nicht gesetzt!
Hostname für NX: XXX
Hostname für WW: Nicht gesetzt!
Hostname für SJ: Nicht gesetzt!
Hostname für DJ: Nicht gesetzt!
Hostname für DD: Nicht gesetzt!
Fehler bei Aufruf von: XXX (<urlopen error [Errno -3] Try again>, timeout=30s)
Fehler bei der Verbindung mit MyJDownloader: 
Verbindungsversuch 1 mit My JDownloader gescheitert. Gerätename: JDownloader_automation
Erfolgreich mit My JDownloader verbunden. Gerätename: JDownloader_automation
Der Zugriff auf NX funktioniert!
Ein Film ohne IMDb-ID wurde in Ombi angefordert und kann nicht verarbeitet werden.
Ein Film ohne IMDb-ID wurde in Ombi angefordert und kann nicht verarbeitet werden.
Ein Film ohne IMDb-ID wurde in Ombi angefordert und kann nicht verarbeitet werden.
Ein Film ohne IMDb-ID wurde in Ombi angefordert und kann nicht verarbeitet werden.
Ein Film ohne IMDb-ID wurde in Ombi angefordert und kann nicht verarbeitet werden.
Ein Film ohne IMDb-ID wurde in Ombi angefordert und kann nicht verarbeitet werden.
2023-02-23 11:14:56 - Alle Suchläufe ausgeführt (Dauer: 00:03:55)!
2023-02-23 11:14:56 - Die Ombi-Suche lief für: 42 Filme und 28 Serien
-----------Wartezeit bis zum nächsten Suchlauf: 00:32:35-----------
```

### Screenshots

Haken = Richtig, unterstrichen sind fehlerhafte Suchen (unerwünschte Ergebnisse)
![grafik](https://user-images.githubusercontent.com/59828746/220881888-f6c6f4f5-3dee-4fd9-92e1-d96b7a995448.png)

**Comment by rix1337** [comment]
@kroeberd  gutes Issue. Problem ist nachgestellt.
Liegt vermutlich daran, dass SD/480p bisher eher stiefmütterlich behandelt wurde..

**Comment by kroeberd** [comment]
Danke dir.
