### ISSUE TITLE
[AntiGateHandler] Proxy was created but does not work! [AntiGateHandler] to_decrypt - Error: (400, 'Entschlüsselung gescheitert!')

### ISSUE THREAD

**Issue by PlanetDyna** [rix1337/FeedCrawler#710]
### Hast du die README gelesen?

- [X] Ich habe die README gelesen

### Gibt es bereits ein Issue für das Problembild?

- [X] Ich habe ältere, offene und geschlossene Issues überprüft

### Hast du die Discussions überprüft?

- [X] Ich habe die Diskussionen gelesen

### Enthält die Problembeschreibung einen oder mehrere Hostnamen?

- [X] Nein, ich habe keine Hostnamen in der Problembeschreibung hinterlegt.

### Laufzeitumgebung

```markdown
Used FeedCrawler Version: 16.4.4
```

### Beschreibung

FeedCrawler find new item but FeedCrawler-Helper shows the following error message:

### Fehlermeldungen aus dem Log

```text
[AntiGateHandler] Proxy was created but does not work! [AntiGateHandler] to_decrypt - Error: (400, 'Entschlüsselung gescheitert!')
```

**Comment by rix1337** [comment]
Bestehende offene bzw. geschlossene issues nicht geprüft.

https://github.com/rix1337/FeedCrawler/issues/699

**Comment by rix1337** [comment]
@mx-hero hat per Discord mitgeteilt, dass vermutlich der Proxy-Aufruf über die externe IP-Adresse zu Problemen führt.
Ab dem nächsten Release wird stattdessen die lokale Adresse des Sponsors Helpers übernommen und für den Proxy-Aufruf verwendet.
