### ISSUE TITLE
Fehlerhafte URL Übergabe bei NX

### ISSUE THREAD

**Issue by mx-hero** [rix1337/FeedCrawler#717]
### Hast du die README gelesen?

- [X] Ich habe die README gelesen

### Gibt es bereits ein Issue für das Problembild?

- [X] Ich habe ältere, offene und geschlossene Issues überprüft

### Hast du die Discussions überprüft?

- [X] Ich habe die Diskussionen gelesen

### Enthält die Problembeschreibung einen oder mehrere Hostnamen?

- [X] Nein, ich habe keine Hostnamen in der Problembeschreibung hinterlegt.

### Laufzeitumgebung

```markdown
- FeedCrawler Version: 17.0.5
- Letzte funktionierende FeedCrawler-Version:
- Betriebssystem: unraid
- Docker: ja
- Sponsors-Helper-URL: ja
- FlareSolverr-URL: ja
```

### Beschreibung

Der Crawler übergibt die URL ohne die Domain an den Helper.
Im Screenshot sieht man das Ergebnis. Es fehlt NX

### Fehlermeldungen aus dem Log

```text
Keine Fehlermeldung vorhanden
```

### Screenshots

![image](https://user-images.githubusercontent.com/6332374/222830694-7487772e-939e-4eb5-8811-5d5d3ef1277a.png)

**Comment by rix1337** [comment]
@mx-hero in welchem Kontext tritt das Verhalten genau auf? Stell bitte einen Debug-Log bereit. Außerdem deine Feedcrawler.db und .ini

@kroeberd kannst du das Verhalten bestätigen? Bei dir lief NX von Anfang an wie gedacht, richtig?

**Comment by rix1337** [comment]
@mx-hero 
Was zeigt dein Screenshot? Den Helper oder einfach das Ergebnis, wenn du im FeedCrawler das Release aufrufst?

**Comment by mx-hero** [comment]
> @mx-hero in welchem Kontext tritt das Verhalten genau auf? Stell bitte einen Debug-Log bereit. Außerdem deine Feedcrawler.db und .ini
> 
Mir ist in der WebUi des Helpers aufgefallen das die Seite nicht angezeigt werden konnte. Dann habe ich im Crawler das Release aufgerufen und gemerkt das da vorn NX fehlt, im helper ebenso. Wenn ich es per Hand nachtrage wird das Release ordnungsgemäß angezeigt und im Log des Crawlers in der WebUi wird Titel / Größe auch richtig angezeigt. Der Link passt nur nicht.

Die .db und .ini hier einfach hochladen oder wie möchtest du die haben?

**Comment by mx-hero** [comment]
Hab gerade die Gegenprobe über die Web Suche gemacht. Da übergibt er die URL richtig und alles funktioniert. 
Vll war es nur eine Ausnahme?!? 
Wenn es von @kroeberd keine Bestätigung gibt würde ich das Issue erstmal stilllegen und weiter beobachten. Wenn es nochmal auftritt melde ich mich.

**Comment by rix1337** [comment]
@mx-hero  mir ist noch nicht klar, in welchem Kontext der fehlerhafte Link entstanden ist.
Web-Suche? Feed-Suche? Beim Captcha lösen durch den Helper?

**Comment by rix1337** [comment]
Fehlermeldung ist seit 3 Tagen inaktiv. Bitte innerhalb eines Tages aktualisieren oder kommentieren, sonst wird diese geschlossen.

**Comment by kroeberd** [comment]
Das Problem tritt bei Websuche vermehrt auf. Im Browser ist der Link funktionabel.

Im normalen Log steht nix.

**Comment by kroeberd** [comment]
Wenn ich Ende der Woche Zeit habe Werte ich ein paar Fehlermeldungen (3 Versuche) aus und schicke dir ggf. die Links privat.

**Comment by rix1337** [comment]
> Wenn ich Ende der Woche Zeit habe Werte ich ein paar Fehlermeldungen (3 Versuche) aus und schicke dir ggf. die Links privat.
> 
> Hatte und hab die Woche und letztes Wochenende viel zutun gehabt.

Hat nichts mit diesem Issue zu tun.
Wenn du Fehlversuche hast, ist zu jedem Versuch der Log aus dem Sponsors Helper notwendig.

**Comment by rix1337** [comment]
> Das Problem tritt bei Websuche vermehrt auf. Im Browser ist der Link funktionabel.
> 
> Im normalen Log steht nix.

@mx-hero kannst du bestätigen dass dieses Problem (Link unvollständig) nur bei der Web-Suche auftritt?

**Comment by mx-hero** [comment]
Ich prüfe das heute Abend und gebe dann Rückmeldung.

**Comment by rix1337** [comment]
Fehlermeldung ist seit 3 Tagen inaktiv. Bitte innerhalb eines Tages aktualisieren oder kommentieren, sonst wird diese geschlossen.

**Comment by rix1337** [comment]
Fehlermeldung nicht rechtzeitig aktualisiert oder kommentiert.
