### ISSUE TITLE
FeedCrawler/Helper verweist auf falschen Hoster

### ISSUE THREAD

**Issue by PlanetDyna** [rix1337/FeedCrawler#727]
### Hast du die README gelesen?

- [X] Ich habe die README gelesen

### Gibt es bereits ein Issue für das Problembild?

- [X] Ich habe ältere, offene und geschlossene Issues überprüft

### Hast du die Discussions überprüft?

- [X] Ich habe die Diskussionen gelesen

### Enthält die Problembeschreibung einen oder mehrere Hostnamen?

- [X] Nein, ich habe keine Hostnamen in der Problembeschreibung hinterlegt.

### Laufzeitumgebung

```markdown
- FeedCrawler Version: 17.0.11
- Docker: [ja/nein] Ja
- FlareSolverr-URL: [ja/nein] Nein
```

### Beschreibung

Es werden die Links zu dem falschen Hoster ausgegeben. 
Ist dieser Fehler bekannt?

### Fehlermeldungen aus dem Log

```text
Keine
```

**Comment by rix1337** [comment]
Hier fehlen klar Details. In welchem Kontext und auf welcher Seite tritt das auf?
Es gibt Seiten, bei denen nicht erkennbar ist, um welchen Hoster es sich handelt. Dort wäre das Verhalten tatsächlich bekannt

**Comment by rix1337** [comment]
Ich habe das Verhalten zwar nicht nachstellen können, allerdings eine mögliche Ursache im Umgang mit NK gefunden.
Möglicherweise ist das Problem also in der nächsten Version behoben

**Comment by PlanetDyna** [comment]
Vielen Dank für die Information.
Zur Informationen: Mit den letzten Versionen gab es dieses Problem nicht.

**Comment by PlanetDyna** [comment]
Ich habe gerade die neue Version getestet. Leider bleibt der Fehler bestehen: Es wird RG anstatt DD übergeben. Entsprechend werden keine Downloads gestartet.

**Comment by PlanetDyna** [comment]
> Ich habe das Verhalten zwar nicht nachstellen können, allerdings eine mögliche Ursache im Umgang mit NK gefunden. Möglicherweise ist das Problem also in der nächsten Version behoben

Ich habe gerade die neue Version getestet. Leider bleibt der Fehler bestehen: Es wird RG anstatt DD übergeben. Entsprechend werden keine Downloads gestartet.

Evtl. war meine Fehlerbeschreibung nicht vollständig. Folgendes geschieht beim Helper wenn ein Download per FeedCrawler übergeben wird:

https://abload.de/img/screenshot2023-03-211cverz.png

**Comment by rix1337** [comment]
Fehlermeldung ist seit 3 Tagen inaktiv. Bitte innerhalb eines Tages aktualisieren oder kommentieren, sonst wird diese geschlossen.

**Comment by PlanetDyna** [comment]
Fehler besteht weiterhin.

**Comment by rix1337** [comment]
Fehlermeldung ist seit 3 Tagen inaktiv. Bitte innerhalb eines Tages aktualisieren oder kommentieren, sonst wird diese geschlossen.

**Comment by rix1337** [comment]
@PlanetDyna dein Screenshot zeigt den Helper. D.h. das Problem liegt vermutlich nicht im FeedCrawler?
Um mit der Lösung zu beginnen, beschreib bitte möglichst genau
1. Deine Erwartungshaltung (was hast du eingestellt, was denkst du, dass dadurch geschehen sollte)
2. Was geschieht stattdessen

**Comment by rix1337** [comment]
Bitte mit ausreichend Infos erneut öffnen.
