### ISSUE TITLE
[Sponsors Helper] Links werden nicht aufgerufen - Fehler: Resource is in more private address space local

### ISSUE THREAD

**Issue by 9Mad-Max5** [rix1337/FeedCrawler#740]
### Hast du die README gelesen?

- [X] Ich habe die README gelesen

### Gibt es bereits ein Issue für das Problembild?

- [X] Ich habe ältere, offene und geschlossene Issues überprüft

### Hast du die Discussions überprüft?

- [X] Ich habe die Diskussionen gelesen

### Enthält die Problembeschreibung einen oder mehrere Hostnamen?

- [X] Nein, ich habe keine Hostnamen in der Problembeschreibung hinterlegt.

### Laufzeitumgebung

```markdown
- FeedCrawler Version: 18.0.5
- Letzte funktionierende FeedCrawler-Version: n.A
- Betriebssystem: unix
- Docker: [ja]
- Sponsors-Helper-URL: [ja]
- FlareSolverr-URL: [ja]
```

### Beschreibung

Der Crawlerhelper fügt die Links nicht automatisch hinzu. Jedes Mal muss von Hand in dem Browser auf den Knopf geklickt werden, damit es weiter geht.
Das kann ja nicht wirklich die Idee gewesen sein.
Während anschließend der Prozess erfolgreich ist und der Link zu JD und FC hinzugefügt wird scheint es als würde die selenium Button detection nicht arbeiten oder was Ähnliches.

### Fehlermeldungen aus dem Log

```text
Keine Meldung im Log
```

### FeedCrawler.ini

```text
[FeedCrawler]
auth_user = 
auth_hash = 
myjd_user = secret|VVbnUCk33pNPdGpzrBbYuvMjfvoSQk/8YoU+gv+fRwk=
myjd_pass = secret|s/CWVGT67aJ6W56S9t54iAdzHWlur+/30/IBpTpHguI=
myjd_device = nas
port = 9090
prefix = 
interval = 20
flaresolverr = http://172.10.30.25:8191
english = False
surround = False
one_mirror_policy = True
packages_per_myjd_page = 5
myjd_auto_update = False
force_ignore_in_web_search = False
sponsors_helper = http://172.10.30.22:9700

[Hostnames]
dj = secret|j734hwG51SK3NFL/9wxb2Q==
fx = secret|e+wq8/z2f3QOgFRWuxV2kQ==
nk = secret|5Q79gHGBBuPnf4fSm0uUIg==
dd = secret|Nxe0DgwF5TImjhJZkUgk3JE1n1PgMqtiyWh1tvXr8FM=
sf = secret|8rz0UwwwV4fzDrKIbDUj6Q==

[Hosters]
rapidgator = True
turbobit = False
ddl = True
filefactory = False
uptobox = False
1fichier = False
filer = True
nitroflare = False
ironfiles = False
k2s = False
katfile = False

[Notifications]
homeassistant = 
pushbullet = 
telegram = 
pushover = 
discord = 

[Ombi]
url = http://172.10.30.20:3579
api = secret|1+vu480pgC220dTXSG7mcqJOMBFHC+Gc+PUcgzzaSkb2GLZhEAJcgwkbGOtl9SzU

[Crawljobs]
autostart = True
subdir = True
subdir_by_type = False

[ContentAll]
quality = 1080p
search = 30
ignore = cam,subbed,xvid,dvdr,untouched,remux,avc,pal,md,ac3md,mic,xxx,aacmd
regex = False
cutoff = True
enforcedl = False
crawlseasons = True
seasonsquality = 1080p
seasonpacks = True
seasonssource = hdtv|hdtvrip|tvrip|web|web-dl|webrip|webhd|netflix*|amazon*|itunes*|bluray|bd|bdrip
imdbyear = 2010
imdb = 8.1
hevc_retail = True
retail_only = False
hoster_fallback = False

[ContentShows]
quality = 1080p
rejectlist = xvid,subbed,hdtv
regex = False
hevc_retail = True
retail_only = False
hoster_fallback = False

[CustomDJ]
quality = 1080p
rejectlist = xvid,subbed
regex = False
hoster_fallback = False

[CustomDD]
hoster_fallback = False

[CustomF]
search = 3

[Overseerr]
url = 
api = 

[SponsorsHelper]
max_attempts = 3
hide_donation_banner = True

[Plex]
url = https://46-142-178-30.ccbe912b126642519a5d5af47cd7a492.plex.direct:32400
api = secret|c40lwP3RcVVKJ2Drt0IM5UNg0rMoFn+VV2TeKV3m3kQ=
client_id = secret|F3w/xHh0uMzPFmMQZQmxnw==
pin_code = 
pin_id = 

[Cloudflare]
wait_time = 12
```

**Comment by rix1337** [comment]
Da mein helper mit FC links Problemlos rennt, mehr Details bitte Screenshots.

Was konkret schief läuft kann ich hier noch nicht erkennen @9Mad-Max5

**Comment by 9Mad-Max5** [comment]
![2023-04-21 14_56_55-1cf8491ef868_1 und 37 weitere Seiten - Persönlich – Microsoft​ Edge](https://user-images.githubusercontent.com/29258083/233641837-6eec5949-384e-458c-9dd9-0eefafde4b6c.png)
So sieht das bei mir aus und es geht dann einfach nicht weiter also er löst den Link nicht.
Warum verstehe ich auch nicht

**Comment by rix1337** [comment]
Ich auch nicht. Stell bitte mehr Details bereit, da anhand dieses Screenshots keine fehlerursache erkennbar ist. Schau mal in der Entwickler Console des Browsers im helper nach ob dort Fehler stehen. Schau auch mal in den Netzwerk Tab dort.

**Comment by 9Mad-Max5** [comment]
Scheint ein Problem mit dem Docker Network zu geben
![2023-04-22 10_03_46-Window](https://user-images.githubusercontent.com/29258083/233771347-3f1dad02-b4e5-46e8-be28-f42000cb0049.png)

Auch wenn ich nicht ganz verstehe, wieso die Ports sollten normal passen hatte die nochmal überprüft,

**Comment by rix1337** [comment]
Möglicher Fix: https://chromeenterprise.google/policies/#InsecurePrivateNetworkRequestsAllowed

Das Flag wird ab Sponsors Helper 9.0.6 per Policy gesetzt. Vielleicht schafft dieses Abhilfe.

@9Mad-Max5  bitte um Prüfung und Feedback

**Comment by 9Mad-Max5** [comment]
Gerade neu gepullt sieht gut aus top

**Comment by rix1337** [comment]
Läuft. Danke für das gute Issue!
