### ISSUE TITLE
FeedCrawler Helper does not return links

### ISSUE THREAD

**Issue by PlanetDyna** [rix1337/FeedCrawler#743]
### Hast du die README gelesen?

- [X] Ich habe die README gelesen

### Gibt es bereits ein Issue für das Problembild?

- [X] Ich habe ältere, offene und geschlossene Issues überprüft

### Hast du die Discussions überprüft?

- [X] Ich habe die Diskussionen gelesen

### Enthält die Problembeschreibung einen oder mehrere Hostnamen?

- [X] Nein, ich habe keine Hostnamen in der Problembeschreibung hinterlegt.

### Laufzeitumgebung

```markdown
- FeedCrawler Version: 18.1.0
- Betriebssystem: Unraid
- Docker: [ja/nein] Ja
- Sponsors-Helper-URL: [ja/nein]
```

### Beschreibung

My FeedCrawler helper does not return links. However, they are passed to Anti-Captcha. At least I see that credits are redeemed for this. Port 33333 is open. No error message appears in the log.

My last thought was that it was the hoster.

I have no idea what the problem is?

### Fehlermeldungen aus dem Log

```text
Nothing
```

### FeedCrawler.ini

```text
Nothing
```

**Comment by rix1337** [comment]
Es fehlen:
- Screenshots vom Helper
- Der Log des helpers.
- Der log des FeedCrawlers

Ohne, ist keine Unterstützung möglich.

**Comment by PlanetDyna** [comment]
`  Click'n'Load2FeedCrawler von RiX
  https://github.com/rix1337/ClickNLoad2FeedCrawler
└──────────────────────────────────────────────────┘
Nutze NodeJS 12.22.9 zum Parsen von JavaScript
Nutze OpenSSL 3.0.2 15 Mar 2022 zum Entschlüsseln der Links
Nutze FeedCrawler 18.1.0 zur Übergabe der Links an My JDownloader
Click'n'Load ist verfügbar unter http://127.0.0.1:9666 und http://172.17.0.2:9666
[FeedCrawler Sponsors Helper] Next try in 10 seconds...
[FeedCrawler Sponsors Helper] FeedCrawler available! Starting AntiGateHandler...
[AntiGateHandler] Version 5.0.3 by RiX
[AntiGateHandler] feedcrawler_url=http://192.168.12.202:9090
[AntiGateHandler] anti_captcha_key=52b3be4815a34334343500072323b3507
[AntiGateHandler] custom_hoster=rapidgator
[AntiGateHandler] proxy_folder=/config/
[AntiGateHandler] v.5.0.3
[AntiGateHandler] Creating HTTP proxy at 87.111.222.154:33333 (User: e03njkvyuqfffeesyiie0be Pass: 3rg000oiffefefenbyd6sr)
[FeedCrawler Sponsors Helper] FeedCrawler available! Starting Chrome (Version 111)...
[FeedCrawler Sponsors Helper] Version 9.0.6 by RiX
[FeedCrawler Sponsors Helper] To prevent the '--no-sandbox' warning run this container with the ' --privileged' flag!`

`┌──────────────────────────────────────────────┐
  FeedCrawler v.18.1.0 von RiX
  https://github.com/rix1337/FeedCrawler
└──────────────────────────────────────────────┘
Nutze das Verzeichnis "/config" für Einstellungen/Logs
Hostname für NK: nima4k.org
Erfolgreich mit My JDownloader verbunden. Gerätename: "JDownloader@jdownloader"
Drücke [Strg] + [C] zum Beenden
Der Zugriff auf NK funktioniert!
2023-05-13 15:13:05 - Alle Suchläufe ausgeführt (Dauer: 00:00:33)!
2023-05-13 15:13:05 - Der FeedCrawler-Cache hat 8 HTTP-Requests gespart!
-----------Wartezeit bis zum nächsten Suchlauf: 01:09:48-----------
[Suche/Film] - XX - [NK] -  - https://nXX
https://XX
[CAPTCHA nicht gelöst] - XX
Der Zugriff auf NK funktioniert!`

![Screenshot 2023-05-14 133539](https://github.com/rix1337/FeedCrawler/assets/24763876/8bfc4a14-1049-45a0-b633-de01b480d9b0)

**Comment by rix1337** [comment]
Danke für die Details.
1. Ändere bitte deinen Anti Captcha Key, der war im log sichtbar und kann von Dritten genutzt werden. Ich habe den key aus deinem Kommentar entfernt.
2. Es wird zu keinem Zeitpunkt die reguläre Entschlüsselung genutzt (der helper log ist daher leer)
3. Im FeedCrawler log sieht man, dass es für ein Release zu viele Fehlersuche gab. Daher wurde das Release entfernt.

Du nutzt scheinbar den helper für eine der Seiten, die NUR im Browser entschlüsselt werden können.
SJ, DJ oder NX. Welche davon nutzt du konkret?

Mach bitte ein Video vom nächsten Lösungsversuch auf dieser Seite. Nur dadurch lässt sich das Problem genauer eingrenzen.

**Comment by PlanetDyna** [comment]
FF ist working. Can you try NK on your own machine?

**Comment by rix1337** [comment]
Fehlermeldung ist seit 3 Tagen inaktiv. Bitte innerhalb eines Tages aktualisieren oder kommentieren, sonst wird diese geschlossen.

**Comment by PlanetDyna** [comment]
Ich bin jetzt auf FF umgestiegen. Jedoch tritt folgendes auf:

┌──────────────────────────────────────────────────┐
  Click'n'Load2FeedCrawler von RiX
  https://github.com/rix1337/ClickNLoad2FeedCrawler
└──────────────────────────────────────────────────┘
Nutze NodeJS 12.22.9 zum Parsen von JavaScript
Nutze OpenSSL 3.0.2 15 Mar 2022 zum Entschlüsseln der Links
Nutze FeedCrawler 18.1.0 zur Übergabe der Links an My JDownloader
Click'n'Load ist verfügbar unter http://127.0.0.1:9666 und http://172.17.0.6:9666
[FeedCrawler Sponsors Helper] Waiting for AntiGateHandler to be available...
[FeedCrawler Sponsors Helper] Next try in 10 seconds...
[FeedCrawler Sponsors Helper] FeedCrawler available! Starting AntiGateHandler...
[AntiGateHandler] Version 5.0.3 by RiX
[AntiGateHandler] feedcrawler_url=http://192.168.12.202:9090
[AntiGateHandler] anti_captcha_key=XX
[AntiGateHandler] custom_hoster=rapidgator
[AntiGateHandler] proxy_folder=/config/
[AntiGateHandler] v.5.0.3
[AntiGateHandler] Creating HTTP proxy at XX:33333 (User: XX Pass: XX)
[FeedCrawler Sponsors Helper] FeedCrawler available! Starting Chrome (Version 111)...
[FeedCrawler Sponsors Helper] Version 9.0.6 by RiX
[FeedCrawler Sponsors Helper] To prevent the '--no-sandbox' warning run this container with the ' --privileged' flag!
[AntiGateHandler] Decrypting https://filecrypt.co/Container/XX (Password: XX)
[AntiGateHandler] Proxy was created but does not work: HTTPSConnectionPool(host='ident.me', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1499e5d92860>, 'Connection to XX timed out. (connect timeout=None)'))
[AntiGateHandler] to_decrypt - Error: cannot unpack non-iterable bool object

**Comment by rix1337** [comment]
Letztlich ließ sich das Verhalten eingrenzen auf folgende Fehlermeldung:

`[AntiGateHandler] Proxy was created but does not work: HTTPSConnectionPool(host='ident.me', port=443): Max retries exceeded with url: / (Caused by 
ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1499e5d92860>, 'Connection to XX timed out. (connect timeout=None)'))`

Das bedeutet schlicht, dass der Proxy auf Port 33333 anders als im Issue ursprünglich vermutet, nicht nutzbar ist.

**Abhilfe schafft diese Anpassung in OPNsense: "Block private networks" im betroffenen WAN deaktiviert.**
