### ISSUE TITLE
Keine Verbindung zu MY JD

### ISSUE THREAD

**Issue by Krepton38** [rix1337/FeedCrawler#747]
### Hast du die README gelesen?

- [X] Ich habe die README gelesen

### Gibt es bereits ein Issue für das Problembild?

- [X] Ich habe ältere, offene und geschlossene Issues überprüft

### Hast du die Discussions überprüft?

- [X] Ich habe die Diskussionen gelesen

### Enthält die Problembeschreibung einen oder mehrere Hostnamen?

- [X] Nein, ich habe keine Hostnamen in der Problembeschreibung hinterlegt.

### Laufzeitumgebung

```markdown
- FeedCrawler Version:18.1.0
- Letzte funktionierende FeedCrawler-Version:-
- Betriebssystem:Unraid
- Docker: ja
- Sponsors-Helper-URL: nein
- FlareSolverr-URL: nein
```

### Beschreibung

Ich bekomme wie bereits im Diskussionenbereich beschrieben nicht zum laufen. FeedCrawler kann keine Verbindung zu My JD aufbauen.

Ich habe Jdownloader von jlesage als Container laufen, welches über binhex-privoxyvpn eine VPN verbindung nutzt.
Auf Myjdownloader ist der Container sichtbar und nutzbar. Der Gerätename lautet JD.
Diesen Gerätenamen habe ich bei der Konfiguration von FeedCrawler eingegeben, jedoch erhalte ich die folgende Fehlermeldung:

Fehler bei der Verbindung mit My JDownloader: Device not found 

### Fehlermeldungen aus dem Log

```text
Fehler bei der Verbindung mit My JDownloader: Device not found
```

### FeedCrawler.ini

```text
[Hostnames]
fx = 
sf = 
dw = 
hw = 
ff = 
by = 
nk = 
nx = 
ww = 
sj = 
dj = 
dd = 

[FeedCrawler]
auth_user = 
auth_hash = 
myjd_user = secret|RaHdKgWhh3y39rcIwi3n/BFItzWsjJ9ICnwMiKzO+vc=
myjd_pass = secret|VkKHe+ULM2int5JjTPAVIeX94WTMke+L6RvpPudsyyI=
myjd_device = JD
myjd_auto_update = False
port = 9090
prefix = 
interval = 60
sponsors_helper = 
flaresolverr = 
english = False
surround = 
one_mirror_policy = False
packages_per_myjd_page = 3
force_ignore_in_web_search = False

[Crawljobs]
autostart = True
subdir = True
subdir_by_type = False

[Notifications]
discord = 
telegram = 
pushbullet = 
pushover = 
homeassistant = 

[Hosters]
ddl = True
rapidgator = True
1fichier = True
filer = False
turbobit = False
filefactory = False
uptobox = False
nitroflare = False
k2s = False
katfile = False
ironfiles = False

[Ombi]
url = 
api = 

[ContentAll]
quality = 1080p
search = 10
ignore = cam,subbed,xvid,dvdr,untouched,remux,mpeg2,avc,pal,md,ac3md,mic,xxx
regex = False
cutoff = True
enforcedl = False
crawlseasons = True
seasonsquality = 1080p
seasonpacks = False
seasonssource = web-dl.*-(tvs|4sj|tvr)|webrip.*-(tvs|4sj|tvr)|webhd.*-(tvs|4sj|tvr)|netflix.*-(tvs|4sj|tvr)|amazon.*-(tvs|4sj|tvr)|itunes.*-(tvs|4sj|tvr)|bluray|bd|bdrip
imdbyear = 2020
imdb = 6.5
hevc_retail = False
retail_only = False
hoster_fallback = False

[ContentShows]
quality = 1080p
rejectlist = XviD,Subbed,HDTV
regex = False
hevc_retail = False
retail_only = False
hoster_fallback = False

[CustomDJ]
quality = 1080p
rejectlist = XviD,Subbed,HDTV
regex = False
hoster_fallback = False
```

**Comment by Krepton38** [comment]
Hab den Fehler gefunden.

Man muss die Konfiguration über die .ini immer ändern. Eine Änderung über die Containereinstellungen in Unraid werden nicht in die .ini geschrieben bzw. übernommen.

**Comment by rix1337** [comment]
Danke für das gut geschrieben issue @Krepton38 

Die Angabe per Unraid Parameter muss eigentlich auch funktionieren.
Ich schau mir das nochmal bei Gelegenheit genauer an.

**Comment by Erik262** [comment]
> Hab den Fehler gefunden.
> 
> Man muss die Konfiguration über die .ini immer ändern. Eine Änderung über die Containereinstellungen in Unraid werden nicht in die .ini geschrieben bzw. übernommen.

Tatsache! musste ich beim selben setup ebenfalls feststellen!
