### ISSUE TITLE
Lädt von einer Datei irrtümlicherweise mehrere Versionen

### ISSUE THREAD

**Issue by PlanetDyna** [rix1337/FeedCrawler#750]
### Hast du die README gelesen?

- [X] Ich habe die README gelesen

### Gibt es bereits ein Issue für das Problembild?

- [X] Ich habe ältere, offene und geschlossene Issues überprüft

### Hast du die Discussions überprüft?

- [X] Ich habe die Diskussionen gelesen

### Enthält die Problembeschreibung einen oder mehrere Hostnamen?

- [X] Nein, ich habe keine Hostnamen in der Problembeschreibung hinterlegt.

### Laufzeitumgebung

```markdown
- FeedCrawler Version: 18.1.0
- Betriebssystem: Unraid
- Docker: Ja
```

### Beschreibung

Der FeedCrawler stellt von einer Datei mehrere Versionen zur Verfügung. Selbst wenn die Bezeichnung der Datei sich nur geringfügig unterscheidet (siehe Beispiel unten). Andere Benutzter berichten von selben Problem. 
Das Verhalten ist u.U. nicht abhängig von einem bestimmten Hostname.

2023-08-14 12:55:42 | Datei1.2023.DV.2160p.WEB.h265-GRUPPE
2023-08-14 12:55:41 | Datei1.2023.HDR.2160p.WEB.h265-GRUPPE

### Fehlermeldungen aus dem Log

```text
Es kommt zu keinem Fehler.
```

### FeedCrawler.ini

```text
Nicht relevant
```

**Comment by rix1337** [comment]
Fehlermeldung ist seit 3 Tagen inaktiv. Bitte innerhalb eines Tages aktualisieren oder kommentieren, sonst wird diese geschlossen.

**Comment by rix1337** [comment]
Fehlermeldung nicht rechtzeitig aktualisiert oder kommentiert.

**Comment by rix1337** [comment]
Konkrete Beispiele wären sinnvoll. Gern per Discord-PN.

Bis auf weiteres zu diffus zur weiteren Bearbeitung.

**Comment by rix1337** [comment]
Bisher nicht reproduziert
