### ISSUE TITLE
Verbindung zu JDownloader instabil/Fehlermeldung bei Abruf

### ISSUE THREAD

**Issue by 9Mad-Max5** [rix1337/FeedCrawler#770]
### Hast du die README gelesen?

- [X] Ich habe die README gelesen

### Gibt es bereits ein Issue für das Problembild?

- [X] Ich habe ältere, offene und geschlossene Issues überprüft

### Hast du die Discussions überprüft?

- [X] Ich habe die Diskussionen gelesen

### Enthält die Problembeschreibung einen oder mehrere Hostnamen?

- [X] Nein, ich habe keine Hostnamen in der Problembeschreibung hinterlegt.

### Laufzeitumgebung

```markdown
- FeedCrawler Version: latest
- Letzte funktionierende FeedCrawler-Version: latest
- Betriebssystem: -
- Docker: [ja]
- Sponsors-Helper-URL: [ja]
- FlareSolverr-URL: [ja]
```

### Beschreibung

Wenn ich den JDownloader Reiter öffne im Web bekomme ich die Meldung JDownloader konnte nicht erreicht werden mit folgender Meldung im Log.
Auch ein Neustart des JDownloaders führen zu keinem Ergebnis.

### Fehlermeldungen aus dem Log

```text
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/feedcrawler/jobs/package_watcher.py", line 50, in watch_packages
    myjd_packages = get_info()
                    ^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/feedcrawler/providers/myjd_connection.py", line 392, in get_info
    packages_in_downloader = get_packages_in_downloader()
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/feedcrawler/providers/myjd_connection.py", line 136, in get_packages_in_downloader
    links = shared_state.get_device().downloads.query_links()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/feedcrawler/external_tools/myjd_api.py", line 657, in query_links
    resp = self.device.action(self.url + "/queryLinks", params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/feedcrawler/external_tools/myjd_api.py", line 862, in action
    response = self.myjd.request_api(path, http_action, params,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/feedcrawler/external_tools/myjd_api.py", line 1230, in request_api
    response = self.__decrypt(self.__device_encryption_token,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/feedcrawler/external_tools/myjd_api.py", line 968, in __decrypt
    decrypted_data = unpad(decryptor.decrypt(base64.b64decode(data)))
                                             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/base64.py", line 88, in b64decode
    return binascii.a2b_base64(s, strict_mode=validate)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
binascii.Error: Invalid base64-encoded string: number of data characters (7129) cannot be 1 more than a multiple of 4
```

### FeedCrawler.ini

```text
[FeedCrawler]
auth_user =
auth_hash =
myjd_user = secret|VVbnUCk33pNPdGpzrBbYuvMjfvoSQk/8YoU+gv+fRwk=
myjd_pass = secret|s/CWVGT67aJ6W56S9t54iAdzHWlur+/30/IBpTpHguI=
myjd_device = nas
port = 9090
prefix =
interval = 20
flaresolverr = http://192.168.4.21:8191
english = False
surround = False
one_mirror_policy = True
packages_per_myjd_page = 5
myjd_auto_update = False
force_ignore_in_web_search = False
sponsors_helper = http://192.168.4.21:9700

[Hostnames]
dj = secret|j734hwG51SK3NFL/9wxb2Q==
fx = secret|e+wq8/z2f3QOgFRWuxV2kQ==
nk = secret|5Q79gHGBBuPnf4fSm0uUIg==
sf = secret|8rz0UwwwV4fzDrKIbDUj6Q==
dw = secret|XhEumzzy6H7jEYE2R0tSmw==
sj = secret|zaf6Th3oeu188ZOHckgLG15HcglhaUOPR5NhBqIVoWk=
nx = secret|QBX4+CMFAbamXF/4uAy3Pg==

[Hosters]
rapidgator = True
turbobit = False
ddl = True
filefactory = False
uptobox = False
1fichier = False
filer = True
nitroflare = False
ironfiles = False
k2s = False
katfile = False

[Notifications]
homeassistant =
pushbullet =
telegram =
pushover =
discord =

[Ombi]
url = http://192.168.4.21:3579
api = secret|1+vu480pgC220dTXSG7mcqJOMBFHC+Gc+PUcgzzaSkb2GLZhEAJcgwkbGOtl9SzU

[Crawljobs]
autostart = True
subdir = True
subdir_by_type = False

[ContentAll]
quality = 1080p
search = 30
ignore = cam,subbed,xvid,dvdr,untouched,remux,avc,pal,md,ac3md,mic,xxx,aacmd
regex = True
cutoff = True
enforcedl = False
crawlseasons = True
seasonsquality = 1080p
seasonpacks = True
seasonssource = hdtv|hdtvrip|tvrip|web|web-dl|webrip|webhd|netflix*|amazon*|itunes*|bluray|bd|bdrip
imdbyear = 2010
imdb = 8.1
hevc_retail = False
retail_only = False
hoster_fallback = False

[ContentShows]
quality = 1080p
rejectlist = xvid,subbed,hdtv
regex = False
hevc_retail = True
retail_only = False
hoster_fallback = False

[CustomDD]
hoster_fallback = False

[CustomF]
search = 3

[Overseerr]
url =
api =

[SponsorsHelper]
max_attempts = 3
hide_donation_banner = True

[Plex]
url = https://192-168-4-21.ccbe912b126642519a5d5af47cd7a492.plex.direct:32400
api = secret|c40lwP3RcVVKJ2Drt0IM5UNg0rMoFn+VV2TeKV3m3kQ=
client_id = secret|F3w/xHh0uMzPFmMQZQmxnw==
pin_code =
pin_id =

[Cloudflare]
wait_time = 12
```

**Comment by rix1337** [comment]
Wirf mal myjd_user und pass aus der ini 

Rest kann bleiben aber user und pass musst du von vorne einrichten. 

Wenn das hilft mach ich hier zu ;)

**Comment by 9Mad-Max5** [comment]
Sehr interessant, scheint geklappt zu haben.
Gab es ein Update, was den CBC Mode geändert hatte?

**Comment by rix1337** [comment]
Nichts dergleichen. War nur die naheliegendste Erklärung dass da was falsch gespeichert war. Wenn das nochmal auftritt prüf ich das genauer

**Comment by 9Mad-Max5** [comment]
Zu früh gefreut kaum hat es einmal geklappt ist der Fehler wieder da sehr interessant

**Comment by 9Mad-Max5** [comment]
![image](https://github.com/rix1337/FeedCrawler/assets/29258083/f85cf086-c252-4867-85e0-efd0a58a8a35)
![image](https://github.com/rix1337/FeedCrawler/assets/29258083/925e8124-a801-4721-840e-afee5809d516)

Hier ein paar screenshots aus dem debugger

**Comment by rix1337** [comment]
Stackoverflow sagt data ist vermutlich kein korrekter base64 String 

so deute ich aus der Ferne den Fehler im Screenshot.

Paste mal data aus dem debugger hier rein.

https://stackoverflow.com/questions/2941995/python-ignore-incorrect-padding-error-when-base64-decoding

**Comment by rix1337** [comment]
Nein hier

Im stackoverflow Beitrag stehen verschiedene Lösungswege wenn data bei dir wirklich korrupt ist.

**Comment by 9Mad-Max5** [comment]
'3x7b1JawRuBAkYDfM6RPZl7hTv4YKf32BaxpIyF7ICb0QKrrlX1AZ2FWseksrdz7MpY5GfDw7AWJ0WB5NNZzRZ41wytxWp5LcRm/2vD2+obAL30Bq6E56Lny14AqDOjT5dbqtwBuFFI3iGK4LqJKYklWLp8V0ZDMtpZHye6gdhrkXXgdHyjEFlnpAiL9NtnC3gy70PlIuZxGuY9a/UlrNDOnD3w/SlhS9DuIVhhbofF5UUZyEYuVW9aYqIeKg8C9y+G8+AmeSXD4tUWe+bAP1PB6ETFcVeaOfI1h1LbIeiBmLHxzTE+ELcEILCOZmSbFmPV4kKHUD4724A/d0BiTOHTblZcZMfih5hguafnGtxr4ZOwf3bhPz+fk+vhPeuf2nh7mckndUVM5zybYCbo43lPR+x8pTKwS+N2X+vhKmXAIRTaFsbWoGVUB0UFbbMTILgCn1xMOPa68d7aOKUoq0ogNsPW/bk5J+9umJ4cVfbkgjbQl1xfc44XwSxcqoqg4qRrCKGLXCkWHa6KA3ExQ4XFAGzrDF9h9ozf0+wgxzK24NfkbdeWKLmCFdLn3gxQIWnidHoYd7sKECR6hahwIQeyrEtdSL/Nf3T/tvFYf1w501rwyMrULHnxUaTGVf9UQursIHxJn1yFso5IsZMvI3mKI+soZsEuNtBop3VFaUjV6q96TqFjBdORTyTKxexEnsY08bdAqH87voplzO3pP9RbkuIkQzrvO8PeyA3IPd3L1DgcGBhRiDoZ7L12m2hlpusliF2KCzLMGTmERKAJfoKIGWPqHP+nE66/uG4fQDEbi/EyMN4pxY4oRQizK4OCGbg5GkZ0ZUlVgVSistpI67SJkyAsl9N3Pus7T90m2PgS3fJatj3dkSj0eHnedo79ufGs7N2Qba30E4FJEJylEciW2VsdBCu2kH9W7gZECcoFgfUlDo1suQ1OlJiioZcrmGgUaj2Zg6x/y3em7eJddQQssDKnOd+lN/4vCXpOZh2G/COplDIPITMYuDknizg2usPjrzafKiZbhH38amVPcTSnYHP+q8RYP7r52jUNt91wRCNu94smFvB8SteDR1aLtRzJxDkApLCUxy29V7ApO/02IKdLc4tPxoIQV7Wig2HQGZycQ0R4I5zplhzDFkg8Oqt4g3p8PxU6Cy/dfDSCbzGBuJXhA7lNQ85XOoy6pqShO2bc57bxTCuD+5xce68RW+ulysPvfydMS/jXrGZg9mzk0Sa8Y9o7Kyt7g7bdtQCpmAB7ktzpdN47hWzab7kHMR6IYErJt3H2OTqXFe6gUptgI9fqQRIZoB44ozvxJGeo4cK3ArnnAc+EMJxM4B6wvCUWTVdUAqowuboAeKFbQTZdxcGd2YDUQ5kcrHF/ceQMLqLribaUiFk37ZxIt7EeSJy8GltxTJVkqqGhYutIYf9j7dn1SfEM28vcHs/c3VVNK9PVbhSBSATyyK43EqtW/3WhLpJdkAjzz9+IEOYgR4slJ6sUFSEi/CAu18Hc6ctzBBuQ517vlYBXB2O7xL0Hnz+eCmIibJ9BfI0rfDeEd9fVHPq4lZy5Xg69bM4P8g+nUhiCp9ZhnO0lWWTnGLZjNGL9n46Axvg7KNE4MU3KHPKOLrHf0Wdz8+BWpye4b7QGFbYxQnJqDiA4ik4XFhOan806JZ/Vzv+pS0ScYU6J1slcaIn2WnNIuTTHcP5xY1KZZ7PaeIph+53Gg+VOA9fIKj4tzUPGzWP18AO3lWpTQEe5fjOAxDcolmkj/Wk2WHwo7GqU1OcpVYB5dYRkOhEc/o/b4Xu97im8+37CfmrQay4ZiHQip2jyIRNwmgs6H1MvH+zSgyh0gkn07p07WWHi/9uKYkkKxp+Hri6gjc8ARRVxksfRqQhUlP6whnR/YqGWbq14jHVw4H4brr96nQdKdQ/fjuahcCdT3DEJqFRka7rOQ3oitA3jG/fNH8+Givi3uZRblMy7dwJavKz0BHLQYJcXUlRWUWQ5GYPi3rrDaAMaeLCyyg6ZMtBMBrxqkN1Kb3KoJ6ROyq/nc/axO21nMM0OZ198NE95mk7LxGIC6KZks8P+7vRiWdu+1eievG6vWmeykpXc+/L06DxpELqB/Zz4rOmTMw+Yokjs8+MLP/uM23TLESNmD2kM3jlJmrT9BAloaXMrp/2U+bqZy4Di5s8an9mHzgj/CPr5Qrx+M1KrNQslzqRzvbnNuYd+8MBEnZ7uuaownYZCWDCiwg34CypJBz9mP1X7v437HfMNta78qKxx9BDGX9BKOZHgkGCv4Ok2SkyUwvHYHTqPy8ECb/ZJoq1lFQoEA8UVIs4IuMwxlwrVGLYtAArGSFAqmmvdhH2N+RELWzJRyVs2SbVKGeh0Inci2HCNLZ72eNR7Dl+Ah9pGhys/6EPjaDUhCdFvh9gWm5s1nlgBdsJiBTrB1kjYoC6YnBdXnQJxucmsGGEqn3/gfKO6QWUXrn+tzKF2uARaETcS0uV26vUOpwD9zuc8J+ni/IiJ/NzLioHQ93dHD/fBpmUk6TFuAI76IGLyO1vKJOcVgeVLg6xKFzAFavYj4MD+UbABP4vRLE9t18qGFXJyWoAAsAEKqRQ1khxYMNv/S++rYhQ4K1Y/0U5Pm0txEomYLijaeeaP0ajJF6LruJFe2/wXrEi6v0CjsRjKHEqtJXy3c/Giq1Z/2F4s+OmW1A3ad+EwMtP+7/zNUK+rm7bbfqRWrNRUShf6PyLm5ABX6nvGjKcGI9jkrcnLBBejoVb5MsAKXQGVSPMgJMtM0ibhG1D7fP9qIlB0K5+Usz+bOl+bX3eDiQfbQaKyNLdNm/Ve0VVLoQJxD/gaR8yILcAOeAdVDxBFDOX9uKWjEAqSWodinRaN/9T2nujD/QY16unpl45Nmr8aLfuFBk+Kn8hoxdJhfZBOiZZCWyNHz5+qoAP/qgctA+e/FeqzteXDT8489OdQHpfI7VwnS8F6p1uO5ERrXyHtre7RizwEkqiEsIbDoDEb+mMM8NX8+0curwbGZr9xtPtvqKzlcAIV9WnqX682mDBodMnylPkdvBMylTdPxBwUp5nhnF5H7EDTmrqkYFleoNAf/ejf2Jv/q2xZwrZcgi+BwHhNAZHI9pzAAjfV427ik5k9tim7UwHZnm3iNdrCOeu4eroAdfsFhvjAwFoS9682nPQjh/Tm7YTETiPFlNW1os7Zu0DETEF160o8QnvJHjiRlkVHLyAPzZ7n8jZ+drc45nQ9pHWTsUoaP4750PG5Kv2/PGv/DDQRMqk05hxtWlCs72lAzJSTFkVt4nRln3Mun9pFeMfvRU+q2D/HPf7pMDiORhZmrGvrXk+ryHl8vtzCFG0s+2iwLOQaEeAEJNngojzjBivFBRSLGFYP7vwewkVZQVE9UCmjewbWgXFoyfPKhu4OVhlKkaxc34P0QiyqQU2D2SxPmsqoX4S85XIRJ1ffvhpPl3D9UVdPjCmQ0UXnfPWx/lWFcFDzvAYMqjj69kUVL527efPkso0+4Pm8x37jw51IS4TYbMCZwWMcuD4xy5Hs4VTWKuK36yHAwJnD7Q83emBnjmHVim3xUKG/rFr0v050+FrZ4yq+l+s5p+0fgpgn8VumFsldQO1Pq0bdPG7TogmLoGrhtflS8Hw8ZaE14kFOrGrlcJX3TpFwFRJlv6CR7sn1oMAZFYySZ2ihL6lGXzF9VhpHpQUpl/ZKDvI2u0iaVYMQ1dPF9lXCO6r9PyQU8HErb1q1OSjZY7MTJho/CEQwadlMgK++Rhcfu/rneVwbrYVcFsEppHm9BEub058/QQedoyDXT4dW8M+zqSHzAjhb60eHHD+bcAQH/zuHqjtAt3OUGpxryozH2HusOHb/6vyt+lWk0WbMKlIBNC7tESRvO7JncJt/BO5Q4p1S0Q0g+ew78fW7LaBg0qJ9zbE/Pbi7lAizVUkyvABw/Go+IlZrFU4Ddom6tNwKfMvRcqQRkP8dJT7xuqOiCVuEbQmF/nRzjPCPJ/9BEbGTIspK4aopBkz7VPMQ62GQ1Kueb60JvNrs/JWkxeI0QnnjCUUlbmOBTFBJ/R2DYqptxrydH3QgHuZzu0+X16uzfrP9vMD0WfinWezdavVdAygEZr4OwwDcwSCtBjqa4P/T61ZIhx1J/5poWLn9pGMWb/8ZBqh137VCJVhhKde8JtDDxcCaCO37IcbRf3MRWiMAQisgIgS2ywgDY3goZGuIy1PGxxc8vLbrFt2faKmju+C9Dvrsbk417q0PDBCcxjaOBdVH7gc12tJiBpUykz9r2n98HsEOcorYo6zAqlrNxYDwdh9X07j1DeyoDJGUozvIc9n/l+UadjgG44XjMi/1GKDPMG65QcC3CHH4zMQvZmyDAeN3SKT6xe5Q4uZvmZTeSaotaZpdphP+ciLtx0aP3CcrUoNzRervVEqXRbwN2IHxENz+3ZwZ+qt/z/4onjGfDBjz05wUhzWuhdtYZiXgeuRLgjkjJgndI995mntLVh19agUgsUx1XvGLLYqYC9FWaE7Ls039vk9tbqWOQMUOcl2LIehMez2JXOFHt3VZyt/Vq1YMiAhpYeG2sWSSL+dEcE4UcRMrwN9N9AMfWxlf2nZ9YjjDQxPV1vDvCiCUQ6lilN9ksmvUaXs39lHHbuy9BvRFEuDH7uilbXDe5nak2vBvBPGnx8DzPmvE3fY9xeAugRHDOLXlUlbldPWS3HrxL0xDFwCplE8+hN7nQLknbKRCN/NUa3773HCqn2mZTJNlvo998fYLzKrSsoLEIpyJdll3r2TQHv4eD2NdPYixN+2NwDbTGgiJQ9iyu2HtbYwo2LXzCYTQ/pXbGBAnaduA/Q+4axvi3E+5YsSeKzdWnH9wB/zB5ojhdWF3iNQtEa5PsVIfLvhM2RsGI5gDjlq8H3lKNEgxm4EnXMpffrcqQH7OPS3Dx1mvE0PKcwwIX4hiP6frtIvq3ghNdydq5rvTQ1R5KeqsBn++C8CMQyTloUZneY+nH/WqTEZTUrgB3A2Xnafexkz7IPGvgGN+O3S1o9U34jFbhQJaKoLLLTDJV8RFOwYjfCoTkx+m/u7CwBq2tehoqDugovt2aaSX1fbPdH0MA3q5XLfVhs15wKne7sVaflBSfD7/TAEXR3iklCWnjYau3c4qyApJ653LI/Lsx4QamwLBiseXHmMZ9xxWZjVZjuyfMA6h54K8QWdJ1SOwKZZO4rB9sFz2COjtad65NlfYIe9j/e8YpQ5PBRwUvqjjfFEAzA+TqLpuB37tYXnrqTQzj/Q4hYoktCj19I7z75QZHXXexQMAO87X7fQmCWooRhy+uMzaR1VUyacLdnoRQVnebFQySLZL3nqArFoEU0zKQIQBOfltco1vdMbpUPi9UTLRiaDGWav0ZunBOdL/j+oLxXpYYgWSs7eIq8J9SJ2XwnlwGeG1qfskbIsuvhg103IHLsl7Y4f1v6cfLajH6M3v3udJgt1qiFl5T0yl/cH6KtjxqRVCD3yoEj5N+NaPlx1bfl4o2u/I97gAoYqfnGR6/w+SjX/Q8rodksT+IpNY8mChselW8VRH5j5ujM8boE4Q9FdotK+7Yarrxy+j121D9d4fkRtvsXpfLD4usE+K3bTry2KqWBN8wZSOs1wka0wdq1psIx1ioWOwuqQZ1OloMK2LBQWMfDSTnTt5BdSLM2dy5ArNmFOqpteZewOBKobDJZI43909/8FPEjqDK6kOVFFkZ1TgjEthkkSGoKmZjBw7L4iOi/tqiXV7I+LDZrBDqW0Cs6JlbxfATNfGRppz+7hVWE66KnqpJXg5+KLJMGHvgOWPOVdkB86DxfZnWU2VVz6IbA5S1H4S09En6U23o9PY5tYDIafFboyCcTEgNzNB7i2tXh9pBVpXR/ZGwNuh7rmhIN+pnQi7BIsMXHRR7RYqtENaPqNlw68XFnLhOtHVITZ/UWMio2hSJgm6WmoKJdL1GKUXbulb5IlKrSlw03+YWcrahGExY4Spzy5LZcgqNZOEaduA5V6pTUaoNWLci3jSA89Ucv3ctv+rF5Ifte3509HkPy8auBFVQ/AeVKG8erad1hSwkWoxBzFYk2R6bcOm7nWys7BmyaQNIDMjeu5NJtFPhyPE+2W3c/OKDqMLPpyNR6tkqSk9mOqhDVs9No0a0bgEogkhX65Zm0TopTvnxc4oN7qlx9yOd9eSv3EogsGSgjcI628aWtgioP/Tb29cLxkuCIUJhH9+u9905c3nfvyCajRlQ+RfweU5IjIgB6LHtYButzcIS7rs6Z3bDPtl/bAabS6zZ8TKGNHni06W7J3IrGe82BE56HifRXTe7dW2dqtqVISicy26AgVBOqv21YiaBjxtOYK6Yri7rrTEhPbpPG3ZDPSdLsFbp4bwX/pMUpMAxC1qfMLgQRou8fmnpDaEB42FhYUtWMYcjAvVQLwj9YLIV5FwM0z+q9bWsuh5XXWKb5RNNViz9a2ozLfgIZkpER1M5iPtdpRMhnHUjmVFaPvTriN1bFATf3D+z0jinK2jUZucHskaQzc9IqNVfaUdl7u6JY62MzjdiHyuV3YMTex2lCwKf8UuVaZomtqcPtyla7LpLLbtQj4opfQtFlE1V+mmEEOyhxfWURY5zs/Bk/5iAZqbAZ/5BQzbF7F6uGgkytsL4T1ivYjwKa0IGTZ9mLdF2+vD6j5Z2MJC5/EsJExGJmM61ora4G5IYky2Sn1pKTe0Nvzk2aQgoyM+WPSlB5XpIca/5464I0jU1V8bsej/tMBeHtfmkwA/IvD6gbVGhcM8s3PaYOxwz/TkUeqlX/BTKboLxlkAq8xZ1uZ2i02E5x1/mjXFKknGb+be2aw5aafmiiNxk0iUuncjTeyfTPHEio8xn8UehADR75yoMrm/bNRjikWrSlCZqK2iU8mDbBOfAWbkBVXtk7my2tX9Wxwmd+WoaSJBe3l7e66LBIJwrJ/KB/MOCS3hl26s/TzVeiYzM5Chz2y+PsLOj7Am3XeR3AS6ndEDHQwNP+RBf6gkGKMe4m9J6nDGLnyQVR/XD6gjRPl4XMjmZDICfdzx6NmIBsDH74D9FmOFwFkEtNXNT+yWtMHvdXMN5fwWIV+g05hKzMPmNXYwsqtMEZttrg2lPDMn0ZFu9exeHrc3kRieunQJOhki5sEaVh10WSoMutsjsL7tzNFykyhS3hmgtS8A/ik1MTMooCCvWEB5+0NhRZvuL6cZFekelxAJEHl9Ol3oqAf3Q1C/pEHEuMbhqAAidSCwzpQ/MxDbBmab8azdxw3gGBIgKv4qWN2S6I8fwpmb7hAP1pBJr632rYMlAXeLMe4przMDFnuYxfLhM77PwmzSrHIFBg3xd09XK4r2jFGYSnh9Axr8nShrk2NzC5x5RwX2CZA5bAzIqDTxxdu4TPVzteseTEWNMCLDYr9OYZBX9Csym6M0RRzqVmovywg5zTT8pdFaZMzoT6ZY/9IGSI2l0ylo+O2qxAtyAVp9F4oFoVhrmpQHIGwsVmz3QQ5PeMDrXfQe0QpNbd0BjmhbuT+rExyIQN/Rc+hzAmys6OqXEaUaCzNjHsTTGdrldIYdvk376sWaMJD8pxoD8yBiJOYTj3YnzkDYZJFE29e4pqY7Gm9I8DEv3McCRUYF+T+jEhtkrfzCtfRSgD2+5nQbwPqDUQn7X4baWW1b3lQFcAITpuOyIY3ObYFLm7LiuPhcqzjayYtrecI39oRMcpC2GS1LDc7lIX2LpCsSRlIpHKEKR0iHxX85hrzAyxHopcmE3r2vk7N5vPBVR1JjjmJJipV9lLt15TOR8OF6PuwhwTfo0D/ADtS9VNZNeA0rPv36WcXsYkh6KwLusuOFk6oBXbedT7T'

**Comment by rix1337** [comment]
@9Mad-Max5 welchen der Lösungswege von SO hast du schon ausprobiert?

das Verhalten tritt bei mir nicht auf und ist daher vermutlich nur durch dich lösbar ;)

**Comment by 9Mad-Max5** [comment]
@rix1337 Oh Missverständnis von meiner Seite dachte, du wolltest mit dem data Variable mal herangehen.
Setze mich gleich mal dran und schaue, ob es im Debugger wieder kommt.

**Comment by 9Mad-Max5** [comment]
Selbst mit den meisten der Ansätze wird es nicht besser. Es geht nur ein Padding von bis zu 2 == die abgeschnitten werden...
Evtl muss man das packet einfach verwerfen war gerade mein gedanke..

**Comment by rix1337** [comment]
Fehlermeldung ist seit 3 Tagen inaktiv. Bitte innerhalb eines Tages aktualisieren oder kommentieren, sonst wird diese geschlossen.

**Comment by 9Mad-Max5** [comment]
Mit diesem Code habe ich aktuell den Fehler nicht mehr sehen können:

`    def __decrypt(self, secret_token, data):
        """
        Decrypts the data from the server using the provided token

        :param secret_token:
        :param data:
        """
        init_vector = secret_token[: len(secret_token) // 2]
        key = secret_token[len(secret_token) // 2 :]
        decryptor = AES.new(key, AES.MODE_CBC, init_vector)
        # data = self.__base64_decode(data)
        # padded_decrypt = decryptor.decrypt(data)
        # padded_decrypt = decryptor.decrypt(base64.b64decode(data))
        try:
            decrypted_data = unpad(decryptor.decrypt(self.__base64_decode(data)))
        except:
            raise MYJDException(
                "Failed to decode response: {}", data
            )
        
        return decrypted_data

    def __base64_decode(self, s):
        """Add missing padding to string and return the decoded base64 string."""
        s = str(s).strip()
        try:
            return base64.b64decode(s)
        except TypeError:
            padding = len(s) % 4
            if padding == 1:
                return ""
            elif padding == 2:
                s += b"=="
            elif padding == 3:
                s += b"="
            return base64.b64decode(s)`

**Comment by rix1337** [comment]
Sieht gut aus
Schick gern einen PR
Den Check ich dann nochmal mit meinem Testsystem

**Comment by 9Mad-Max5** [comment]
Jop mache ich denke morgen

**Comment by rix1337** [comment]
Guter Pull Request, gutes Issue. Sollte gelöst sein 👍🏻
