### ISSUE TITLE
Feedcrawler funktioniert nicht mehr

### ISSUE THREAD

**Issue by DKeppi** [rix1337/FeedCrawler#782]
### Hast du die README gelesen?

- [X] Ich habe die README gelesen

### Gibt es bereits ein Issue für das Problembild?

- [X] Ich habe ältere, offene und geschlossene Issues überprüft

### Hast du die Discussions überprüft?

- [X] Ich habe die Diskussionen gelesen

### Enthält die Problembeschreibung einen oder mehrere Hostnamen?

- [X] Nein, ich habe keine Hostnamen in der Problembeschreibung hinterlegt.

### Laufzeitumgebung

```markdown
- FeedCrawler Version: 19.2.2
- Letzte funktionierende FeedCrawler-Version: 19.2.2 (älteres Docker Image)
- Betriebssystem: Linux (Synology DS920+ mit DSM 7.2.1)
- Docker: ja
- Sponsors-Helper-URL: nein
- FlareSolverr-URL: nein
```

### Beschreibung

Feedcrawler bringt leere Seite im Browser

Meine Container werden autom. mit dem neuesten latest Docker Image upgedated, da gibt es ja täglich ein neues bei Feedcrawler.
Läuft seit heute nicht mehr, wobei ich nicht sagen kann ob es nicht schon am Samstag/Sonntag nicht mehr ging.
Freitags lief er noch mit dem latest Image

### Fehlermeldungen aus dem Log

```text
s6-supervise feedcrawler: warning: unable to spawn ./run (waiting 60 seconds): Permission denied
```

### FeedCrawler.ini

```text
[Hostnames]
fx = 
sf = 
dw = 
hw = 
ff = 
by = 
nk = 
nx = 
ww = 
sj = secret|cy5YPYJL15JDUxrK+2hiGkpfwoIBivYoyDL835kRows=
dj = 
dd = 

[FeedCrawler]
auth_user = 
auth_hash = 
myjd_user = secret|GO+4PPpwP/hEceAcbf0gHg==
myjd_pass = secret|/a+1E5nB4Tx8S57rGi7hdg==
myjd_device = Kepplomat-jD2
myjd_auto_update = True
port = 9090
prefix = 
interval = 30
sponsors_helper = 
flaresolverr = 
english = False
surround = False
one_mirror_policy = False
packages_per_myjd_page = 5
force_ignore_in_web_search = False

[Crawljobs]
autostart = True
subdir = True
subdir_by_type = False

[Notifications]
discord = 
telegram = 
pushbullet = 
pushover = secret|3lEmLx1oB8WxHokslS+sfxOjvg7bJgvy6I3ZNUow34BzSSX2LGLGdXn7td3kW4XI1nA9af7INY7pmzbg267SWA==
homeassistant = 

[Hosters]
ddl = True
rapidgator = True
1fichier = True
filer = True
turbobit = True
filefactory = False
uptobox = False
nitroflare = False
k2s = False
katfile = False
ironfiles = False

[Ombi]
url = 
api = 

[ContentAll]
quality = 1080p
search = 10
ignore = cam,subbed,xvid,dvdr,untouched,remux,mpeg2,avc,pal,md,ac3md,mic,xxx
regex = False
cutoff = True
enforcedl = False
crawlseasons = False
seasonsquality = 480p
seasonpacks = False
seasonssource = web-dl.*-(tvs|4sj|tvr)|webrip.*-(tvs|4sj|tvr)|webhd.*-(tvs|4sj|tvr)|netflix.*-(tvs|4sj|tvr)|amazon.*-(tvs|4sj|tvr)|itunes.*-(tvs|4sj|tvr)|bluray|bd|bdrip
imdbyear = 2020
imdb = 6.5
hevc_retail = False
retail_only = False
hoster_fallback = False

[ContentShows]
quality = 480p
rejectlist = subbed
regex = True
hevc_retail = False
retail_only = False
hoster_fallback = False

[CustomDJ]
quality = 1080p
rejectlist = xvid,subbed,hdtv
regex = False
hoster_fallback = False

[Cloudflare]
wait_time = 6

[Plex]
url = 
api = 
client_id = 
pin_code = 
pin_id = 

[Overseerr]
url = 
api = 

[CustomF]
search = 3

[CustomDD]
hoster_fallback = False

[SponsorsHelper]
max_attempts = 3
hide_donation_banner = False
```

**Comment by DKeppi** [comment]
Hab das Image 19.2.2 versucht, selbes Problem!
Wenn ich auf 19.2.1 wechsle, läuft der Crawler wieder

**Comment by rix1337** [comment]
Gutes Issue. Das linuxserver baseimage macht gerade generell Probleme..

**Comment by DKeppi** [comment]
Leider wieder dasselbe Problem!

Container läuft zwar, aber im Log steht wieder der Fehler 
s6-supervise feedcrawler: warning: unable to spawn ./run (waiting 60 seconds): Permission denied

**Comment by rix1337** [comment]
Ja. Liegt daran, dass auch das neue baseimage von linuxserver fehlerhaft ist.

Das neue Release entfernt all das und nutzt stattdessen vanilla alpine.
Und um zu verhindern, dass der `latest` tag zwischen Releases kaputt geht, schmeiß ich die Baseimage-Autoupdates raus.

Release 19.2.5 ist da. Sollte wieder laufen.

**Comment by DKeppi** [comment]
Leider nicht:

Process Process-2:
Traceback (most recent call last):
  File "/usr/bin/feedcrawler", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.12/site-packages/feedcrawler/run.py", line 204, in main
    delay = int(arguments.delay)
            ^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '$DELAY'
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/managers.py", line 813, in _callmethod
    conn = self._tls.connection
           ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ForkAwareLocal' object has no attribute 'connection'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.12/site-packages/feedcrawler/web_interface/web_server.py", line 2060, in web_server
    if shared_state_dict["gui"]:
       ~~~~~~~~~~~~~~~~~^^^^^^^
  File "<string>", line 2, in __getitem__
  File "/usr/lib/python3.12/multiprocessing/managers.py", line 817, in _callmethod
    self._connect()
  File "/usr/lib/python3.12/multiprocessing/managers.py", line 804, in _connect
    conn = self._Client(self._token.address, authkey=self._authkey)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 519, in Client
    c = SocketClient(address)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 647, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

**Comment by rix1337** [comment]
Du bist nicht auf version 19.2.5.

**Comment by DKeppi** [comment]
Da war ich wohl zu ungeduldig, hab das latest nochmals geladen und nun klappts wieder!
DANKE!
